### ISSUE TITLE
API Key / Username / Password for DoT

### ISSUE THREAD

**Issue by randypitcherii** [hashmapinc/Drillflow#104]
EPIC

**Comment by randypitcherii** [comment]
EPIC

**Comment by randypitcherii** [comment]
BLOCKED waiting for Username and Password from SLB for DoT

**Comment by randypitcherii** [comment]
Thanks a ton, Chris! We're implementing the DoT auth now using your server!

**Comment by niaalex** [comment]
@randypitcherii @cherrera2001   Is this one still blocked ?

**Comment by cherrera2001** [comment]
nope

**Comment by niaalex** [comment]
@randypitcherii @cherrera2001  disregard
