### ISSUE TITLE
Return proper WITSML response codes

### ISSUE THREAD

**Issue by randypitcherii** [hashmapinc/Drillflow#174]
Drillflow currently sends a mix of valid and not valid response codes. This is not good for true WITSML clients.

Do the following:
- find everywhere that a response code is returned to the client in `StoreImpl`
- refer to the WITSML Store spec for 1311 and 1411 and ensure that each returned response code is valid (simply replace the wrong code with the right code)
- for anything complex that requires code changes outside of `StoreImpl`, please comment the case in this issue and we will create a new set of cards to handle those issues in another card (this keeps things manageable)

NOTES:
- the error codes exist in the code base in a properties file. Make sure that you refer to these values when replacing invalid codes
- COMMENT what you're doing. It is really important that you explain what you're doing here. This can get really buggy fast if we're not smart.

Thanks!

child of #257

**Comment by niaalex** [comment]
@vijaypoojari @randypitcherii  - Vijay please advise the status/ETA for this item.

**Comment by niaalex** [comment]
@vijaypoojari is this item still open?
