### ISSUE TITLE
Fix trajectory JSON serialization

### ISSUE THREAD

**Issue by randypitcherii** [hashmapinc/Drillflow#200]

**Comment by cherrera2001** [comment]
This is part of the attribute "explosion"

**Comment by randypitcherii** [comment]
Json serialization should ignore NULL fields, but currently does not

**Comment by randypitcherii** [comment]
use annotations to address this in the WOL

**Comment by sukhendumukherjee** [comment]
Maven build was failing as MavenReportException: Error while generating Javadoc: .
To Fix the Javadoc error I added following entry in pom.xml to complete maven build.

<profile>
            <id>disable-java8-doclint</id>
            <activation>
                <jdk>[1.8,)</jdk>
            </activation>
            <properties>
                <additionalparam>-Xdoclint:none</additionalparam>
            </properties>
        </profile>

**Comment by sukhendumukherjee** [comment]
Fixed and merged.Closing this issue.
