### ISSUE TITLE
Add & Update Wellbore Issue in 1.4.1.1

### ISSUE THREAD

**Issue by bbuckles** [hashmapinc/Drillflow#244]
Send in Request for Add or Update to Wellbore in 1.4.1.1.

Expected Results:

Get a successful response back

Observed Results:

Getting 1 returned

<SuppMsgOut>Error updating in store: null</SuppMsgOut>

**Comment by bbuckles** [comment]
Request for Update To Wellbore:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://www.witsml.org/wsdl/120" xmlns:types="http://www.witsml.org/wsdl/120/encodedTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      <q1:WMLS_UpdateInStore xmlns:q1="http://www.witsml.org/message/120">
         <WMLtypeIn xsi:type="xsd:string">wellbore</WMLtypeIn>
         <XMLin xsi:type="xsd:string"><![CDATA[<wellbores xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1">
  <wellbore uidWell="HMa"uid="HM005">
    <nameWell>Cobra1</nameWell>
    <name>Comdr005</name>
  </wellbore>]]></XMLin>
  <OptionsIn xsi:type="xsd:string">returnElements=requested</OptionsIn>
         <CapabilitiesIn xsi:type="xsd:string"/>
          
      </q1:WMLS_UpdateInStore>
   </soap:Body>
</soap:Envelope>

Response:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <ns1:WMLS_UpdateInStoreResponse xmlns:ns1="http://www.witsml.org/wsdl/120">
         <return xmlns:ns2="http://www.witsml.org/wsdl/120">
            <Result>-1</Result>
            <SuppMsgOut>Error updating in store: null</SuppMsgOut>
         </return>
      </ns1:WMLS_UpdateInStoreResponse>
   </soap:Body>
</soap:Envelope>

**Comment by bbuckles** [comment]
Request for Add Wellbore

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://www.witsml.org/wsdl/120" xmlns:types="http://www.witsml.org/wsdl/120/encodedTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      <q1:WMLS_AddToStore xmlns:q1="http://www.witsml.org/message/120">
         <WMLtypeIn xsi:type="xsd:string">wellbore</WMLtypeIn>
         <XMLin xsi:type="xsd:string"><![CDATA[<wellbores xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1">
  <wellbore uidWell="HMb" uid="HM007">
   <nameWell>Zartan2<nameWell>
    <name>GIJoe2</name>
    </wellbore>
</wellbores>]]></XMLin>
         <OptionsIn xsi:type="xsd:string">returnElements=all</OptionsIn>
         <CapabilitiesIn xsi:type="xsd:string"/>
      </q1:WMLS_AddToStore>
   </soap:Body>
</soap:Envelope>`

Response
`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <ns1:WMLS_AddToStoreResponse xmlns:ns1="http://www.witsml.org/wsdl/120">
         <return xmlns:ns2="http://www.witsml.org/wsdl/120">
            <Result>-1</Result>
            <SuppMsgOut>Error adding to store: null</SuppMsgOut>
         </return>
      </ns1:WMLS_AddToStoreResponse>
   </soap:Body>
</soap:Envelope>`

**Comment by cherrera2001** [comment]
Looking at that query it is super not valid witsml...can you double check your query @bbuckles

**Comment by bbuckles** [comment]
Invalid issue. Issue with Soap Request.
