### ISSUE TITLE
Redis Caching

### ISSUE THREAD

**Issue by randypitcherii** [hashmapinc/Drillflow#256]

**Comment by cherrera2001** [comment]
Implement a redis backend for the new caching wrapper.

**Comment by niaalex** [comment]
@cherrera2001  how should we prioritize this item?

**Comment by cherrera2001** [comment]
It needs to be done within the next 2 sprints.

**Comment by niaalex** [comment]
@cherrera2001 please review this one to add the needed detail in order for the team to do analysis for consideration for this sprint.

**Comment by niaalex** [comment]
> @niaalex It needs to be done within the next 2 sprints.
Noted; I will flag this one for completion within the next Sprint.

**Comment by niaalex** [comment]
This item is no longer in scope.
