### ISSUE TITLE
Need to verify that all trajectory elements are returned for a add/get/update flow

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#261]
Need to verify that all trajectory elements are returned for a add/get/update/search flow

**Comment by niaalex** [comment]
Certification test for Trajectory will close this. 

In progress now @ 50% complete.

**Comment by bbuckles** [comment]
Confirmed when testing trajectory that all elements are returned in the Get request in several certification test cases I have executed.

**Comment by niaalex** [comment]
@Mike-d-s  this is the Trajectory card I was referring to in our plan review.  I will add this to this Sprints deliverables.
