### ISSUE TITLE
DEV: LOG: Create the query handler for mapping channel set to log curve info

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#317]

**Comment by niaalex** [comment]
In Progress part of the AddtoStore #364 /no longer blocked

**Comment by niaalex** [comment]
In Progress ETA 4/26 with AddtoStore

**Comment by TessForGithub2** [comment]
Update on this 4/26: This code has been committed. All that is needed is to verify functionality with JUnit tests.

**Comment by TessForGithub2** [comment]
I have created a JUnit card #402 for this item. I will close this card to avoid confusion of doing multiple tasks at the same time.

**Comment by niaalex** [comment]
The mapping is now complete.
