### ISSUE TITLE
Convert the DotClient token cache to ConcurrentHashmap

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#338]
## Summary
Currently the DotClient is currently caching tokens on the heap via a HashMap, when multiple users across threads are accessing this info...theres issues that can cause a deadlock.

This should be an easy one-two line change to the DotClient to change the type to concurrenthashmap.

## Implementation Details

1) In the class com.hashmapinc.tempus.witsml.valve.dot.DotClient find the member variable _cache_

2) Change the type from HashMap to ConcurrentHashmap<> to ensure thread safety

**Comment by TessForGithub2** [comment]
Created a card to address concurrency testing solutions and connected to this card.
