### ISSUE TITLE
Ability to specify full URL for target services endpoint

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#357]
Confirm that the container config includes the ability to specify a full URL (not just the root) for the target services endpoint.

**Comment by TessForGithub2** [comment]
I spoke to Chris just now and confirmed the following:
1. There never was a hardcoded URL.
2. It is in application.yml (already there).
3. Chris updated the documentation to reflect how to edit it and he sent it in the SLB channel.
4. He did some quick testing and it seems to work just fine.

**Comment by sukhendumukherjee** [comment]
application.yml file is updated to refer env file for us to use.Tested with soap ui and looks good.
