### ISSUE TITLE
LOG: Create POJOs - Priority 1

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#362]
**EPIC:**
#361 Log CRUD Implementation
**Sizing:**
S (Small - 2-8 hours)
**Priority:** 
1 - All further work depends upon the generation of the POJOs
**Description:**
1. Use http://www.jsonschema2pojo.org/ to generate Plain Old Java Objects (POJOs) from JSON or JSON-Schema (use defaults; JSON-Schema to POJO option; make sure to generate getters/setters; set package & class name upfront so the tool does all the work; this will be a special LOG object inside Drillflow). There may be some clean-up of the generated POJO.
2. Request Model: POST/PUT/PATCH
               and
    View Model: GET
    Java Object is the union of both of these objects
NOTES:
Channel & Channel Set POJOs will go into _dot.model_.
Child of #361

**Comment by niaalex** [comment]
@cherrera2001  are you able to close this request or is there a block?  Please advise the ETA for your review.
