### ISSUE TITLE
LOG: WMLS_AddToStore - Priority 2

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#364]
**EPIC:**
#361 Log CRUD Implementation
**Sizing:**
L (3-4 Days)
**Priority:**
2
**Description:**
This is the "C" in "CRUD".

1.Remove LOG header & Create Channel Set (Channel Set Model; ChannelSetObj)
2.Then update Channel Set with Log Curve Information (this is the Channel Model; ChannelObj)
3.Add the data (CSV format)
        (tabular view of the 1.4.1.1 log 
         1.3.1.1 vs. 1.4.1.1 <-- different data
         Example:
              Log Data
              1.3.1.1
                    1000, 3.2, 4.6,,9,,,elephant
              1.4.1.1 (their model is closer to this; but take out the 2nd header line)
                    index, tga, rpm, sppa, tft, ..., ..., ...,
                    ft, ft.los, cpm, psi, gpm, ..., ..., ..., ...,
         So, since their model is closer to 1.4.1.1, get as 1.4.1.1 with WITSML Library (but do not 
         modify the WITSML Library since this is NOT WITSML).
         NOTES:
         -->Secondary Index is Depth OR TIME but never BOTH.
         -->IMPORTANT! 1 Channel Set = 1 Log
         -->Do not go nuts with JUnit testing; only functionality & not the Java language
         -->Do NOT put non-WITSML into the WITSML Library; always can use the Library, however.
4. Refer to https://engdmzprism.portal.azure-api.net/docs/services/democore-Slb-Prism-Core-Service-ChannelReader-4/operations/Channels_PostDepthBoundaryAsync  --
This is the Swagger, and reveals the order in which things need to be done. 
![Screen Shot 2019-04-01 at 10 31 22 AM](https://user-images.githubusercontent.com/48033741/55340162-bb2b7f00-5469-11e9-9672-f8fc461bfc57.png)

**Comment by niaalex** [comment]
In Progress ETA 4/26

**Comment by TessForGithub2** [comment]
JUnit is a separate card now.
