### ISSUE TITLE
LOG: WMLS_GetFromStore - Priority 2

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#365]
**EPIC:**
#361 Log CRUD Implementation
**Sizing:**
L (3-4 Days)
**Priority:**
2
(AddToStore must arrive at same time in order for GetFromStore to have something to work with)
**Description:**
This is the "R" in "CRUD".
1. Create POJO
   Create POJO - mapping 1.3.1.1
                           - mapping 1.4.1.1
2. AddToStore in reverse
         Object Transformation as it applies to a schema:
         1.3.1.1 Query --> OBJECT
         1.4.1.1 Query --> OBJECT

          WITSML----->(translate into) ChannelSet -----> DoT (ADD)
          WITSML<-----(translate into) ChannelSet<-----  DoT  (GET)
3. Condition
         time log - time & depth
         depth log - depth

NOTE:
     -->Do not go nuts with JUnit testing; only functionality & not the Java language
     -->Do NOT put non-WITSML into the WITSML Library; always can use the Library, however.. 
4. Refer to:
https://engdmzprism.portal.azure-api.net/docs/services/democore-Slb-Prism-Core-Service-ChannelReader-4/operations/Channels_PostDepthBoundaryAsync
This is the Swagger, and reveals the order in which things need to be done.
![Screen Shot 2019-04-01 at 10 57 34 AM](https://user-images.githubusercontent.com/48033741/55341853-0a26e380-546d-11e9-8407-c8d0ac9a5b51.png)

**Comment by niaalex** [comment]
@TessForGithub2 update test

**Comment by sukhendumukherjee** [comment]
It seems like the POST apis are working but not the GET (everything resulting in 500).

**Comment by niaalex** [comment]
Confirmed SLB is aware of this item c/o Shuping.  Changes in progress.
No ETA at this time.

**Comment by niaalex** [comment]
In progress with ETA to complete 4/25

**Comment by niaalex** [comment]
Reopened to capture additional scope

**Comment by sukhendu555** [comment]
Added the code for following functionality
1. Code added to call well graph QL API to get well name.
1. Code added to call wellbore graph QL API to get wellbore name.

Working on to add wellname and wellborename to place in cache so it can be used in updateinstore functionality.

**Comment by sukhendu555** [comment]
Added code logic to get well name and wellbore name.Will work on to set these into cache.

**Comment by sukhendu555** [comment]
Create a PR to address this Task.

**Comment by sukhendumukherjee** [comment]
We have added logic for logData and logData is returning data from DOT.We are now done all rest call for this card and card can be closed.Separate defects are logged we will address.
