### ISSUE TITLE
LOG: QA SoapUI Testing for WMLS_AddToStore

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#366]
**EPIC:**
#361 Log CRUD Implementation
**Sizing:**
TBD
**Priority:**
1
**Description:**
Will be provided by assigned Hashmap Developer - TBD (DEV team needs to generate the required artifacts: QueryIn, CapabilitiesIn, OptionsIn, Type, but also pointers within the API Guide to help explain the Use Cases)
**DEV Card:**
#364 LOG: WMLS_AddToStore - Priority 2

**Comment by niaalex** [comment]
No longer blocked

**Comment by bbuckles** [comment]
Rolling off project and unassigned myself from this card as a result.

**Comment by niaalex** [comment]
Hand off in progress

**Comment by TessForGithub2** [comment]
1.  Handoff happened on 4/25.
     AddToStore for Log (full transaction) is working in Shehzad's SoapUI environment.
2. As with AddToStore for Well, 4 Assertions have been provided with an AddToStore SoapUI Test:
    a. SOAP Response -> success
    b. Not SOAP Response -> success
    c. Success (Result is 1) -> success
    d. Contains correct UID Return -> will be completed by COB today (4/26)
3. All hardcoding will be replaced by COB today (4/26).
4. ASK: where should Shehzad be committing his tests.

These 2 outstanding pieces to this card will be completed by COB today (4/26) and the card will be closed.

**Comment by niaalex** [comment]
Confirmed c/o ASK: where should Shehzad be committing his tests commit to branch then merge to master

**Comment by TessForGithub2** [comment]
Waiting for a check-in assist from Sukhe; a lot of changes have happened since this past Friday, and so this check-in needs to be correct. But the testing is successful & complete. Should be accomplished by COB today (4.29).

**Comment by shehzadsidi** [comment]
Checked in all test cases in GitHub
