### ISSUE TITLE
LOG: QA SoapUI Testing for WMLS_GetFromStore

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#367]
Sizing:
TBD
Priority:
2
Description:
Will be provided by assigned Developer - TBD
DEV Card:
#365  LOG: WMLS_GetFromStore - Priority 2

**Comment by niaalex** [comment]
No longer blocked

**Comment by bbuckles** [comment]
Un-assigned myself from this card as a result of me rolling off the project.

**Comment by niaalex** [comment]
In Progress ETA 4/25

**Comment by niaalex** [comment]
Hand off from Dev today 4/25

**Comment by TessForGithub2** [comment]
JUnit is a separate card now.

**Comment by niaalex** [comment]
Noted/thank you

 

I will track/report percent complete based on the updates.

**Comment by TessForGithub2** [comment]
1. Handoff occurred on 4/25.
    GetFromStore for Log (based on prior AddToStore for Log (full transaction)) is working in 
    Shehzad's SoapUI environment.
2. As with GetFromStore for Well, 3 Assertions have been provided with a GetFromStore SoapUI 
    Test:
    a. SOAP Response -> success
    b. Not SOAP Response -> success
    c. Success (Result is 1) -> success

The only outstanding element to this card is removing hardcoding, which will be completed by COB today (4/26) and the card will be closed.

**Comment by shehzadsidi** [comment]
Test Case completed and checked in GitHub
