### ISSUE TITLE
Return for requestObjectSelectionCapability=true returns incorrectly formed XML response

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#373]
When executing GetFromStore for Wells query:
```<?xml version="1.0" encoding="UTF-8"?>
<wells xmlns="http://www.witsml.org/schemas/1series" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.witsml.org/schemas/1series  ../xsd_schemas/obj_well.xsd" 
	version="1.4.1.1">
<well />
</wells>
```
with 
```
<OptionsIn xsi:type="xsd:string">requestObjectSelectionCapability=true</OptionsIn>
```

The document header and wells root of the returned XML document doesn't contain the expected info.  The return is expected to provide a compliant Well object response.

Current return for requestObjectSelectionCapability=true
```
<wells xmlns="http://www.witsml.org/schemas/1series"version="1.4.1.1">
<well uid="uid_dfTestWell1">
<name>dfTestWell1</name>
<numGovt>12345</numGovt>
<numAPI>12345</numAPI>
<commonData>
<dTimLastChange>2019-03-08T19:47:27.545Z</dTimLastChange>
</commonData>
</well>
</wells>
```

Normal/expected well return:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<wells version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series" xmlns:ns2="http://www.energistics.org/schemas/abstract">
<well uid="well UID goes here">
<name>
```
...... (return abridged)

Related to #332

**Comment by Mike-d-s** [comment]
#332

**Comment by cherrera2001** [comment]
This is the correct behavior for this option. As per the spec:
Example: A server that supports the country and operator elements (in addition to the mandatory elements and attributes) for well object selection will return the following object when it receives a WMLS_GetFromStore call for a well with requestObjectSelectionCapability=true.
For more information on using requestObjectSelectionCapability (and other OptionsIn parameters), see page Section 6.6.2.1, page 55.

```xml
<wells xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1">
    <well uid="abc">
        <name>abc</name>
        <numGovt>abc</numGovt>
        <country>abc</country>
        <operator>abc</operator>
        <numAPI>abc</numAPI>
        <commonData>
            <dTimLastChange>1900-01-01T00:00:00.000Z</dTimLastChange>
        </commonData>
    </well>
</wells>
```

**Comment by Mike-d-s** [comment]
Objectselection return now contains correct elements, but I'm having trouble getting the return to parse in the SoapUI test using xmlSlurper.  Return currently is:
```
<wells xmlns="http://www.witsml.org/schemas/1series"version="1.4.1.1">
	<well uid="uid_dfTestWell1">
	<name>dfTestWell1</name>
	<numGovt>12345</numGovt>
	<numAPI>12345</numAPI>
		<commonData>
			<dTimLastChange>2019-03-08T19:47:27.545Z</dTimLastChange>
		</commonData>
	</well>
</wells>
```
Parse error reports an expected > or /> when processing the wells element attributes.  Currently the attributes read as:

wells xmlns="http://www.witsml.org/schemas/1series"version="1.4.1.1"

I think a space is required between the namespace and the version.  So the expected is:

wells xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1"
