### ISSUE TITLE
UID Search with Criteria

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#377]
C/O Review Scope for dTimLastChange query Change

Need to validate the mapping for Well getFromStore for the element dTimLastChange and then impact of having to convert to UTC time for non UTC incoming query parameters.
Should pass test for Mike afterwards.

Small
Sprint - 10

**Comment by cherrera2001** [comment]
This connects to #355

**Comment by cherrera2001** [comment]
For this one you will want to follow the same pattern as we did for Trajectory. 

For well you will want to see if any of the following elements are available **In addition** to uid (in the case where there is no uid...this will work anyway as it defaults to the graphql path):

- uid
- name
- numGovt
- numAPI
- commonData.dTimLastChange

For wellbore you will want to see if any of the following elements are available **In addition** to uid (in the case where there is no uid...this will work anyway as it defaults to the graphql path):

- uid
- nameWell
- name
- commonData.dTimLastChange

**Comment by niaalex** [comment]
this was delivered with RTC
