### ISSUE TITLE
QA:All Objects:Extend the test cases for SoapUI

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#380]
SLB is requesting more testing than the certification tool provides and there is a potential need to    extend the test cases for SoapUI.

We will need to discuss the LOE to support this and determine if this will be covered in the current scope or added to an in progress PCR.

Size - Large
Date - TBD 

Pending additional scope discussions.

**Comment by niaalex** [comment]
Dep on JUNIT test EPIC

**Comment by TessForGithub2** [comment]
Update: Already communicated the strategy to the client. Shehzad says to close the card.
