### ISSUE TITLE
DEV: LOG: WMLS_DeleteFromStore

### ISSUE THREAD

**Issue by sukhendumukherjee** [hashmapinc/Drillflow#394]
EPIC:
#361 Log CRUD Implementation
Sizing:
M (2-3 Days)
Priority:
3
(DeleteFromStore must arrive at same time in order for GetFromStore to have something to work with)
Description:
This is the "D" in "CRUD".

NOTE:
-->Do not go nuts with JUnit testing; only functionality & not the Java language
-->Do NOT put non-WITSML into the WITSML Library; always can use the Library, however..
4. Refer to:
https://engdmzprism.portal.azure-api.net/docs/services/democore-Slb-Prism-Core-Service-ChannelReader-4/operations/Channels_PostDepthBoundaryAsync
This is the Swagger, and reveals the order in which things need to be done.

**Comment by niaalex** [comment]
@sukhendumukherjee  you have been assigned and #398 has been renamed to reflect "Handoff for QA For #394 LOG: WMLS_DeleteFromStore"

**Comment by sukhendumukherjee** [comment]
In DeleteFromStore we have following two rest calls

**1. https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channelSets/{uuid}**

From the https://engdmzprism.portal.azure-api.net  portal while passing valid uuid and authentication code (with no body) it's saying 
Response status  for valid uuid - “ee2642c4-baab-40dc-81dd-450e0e80dfca”
Response status
403 Forbidden

Am I doing something incorrect? 

**2. https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/{mnemonic}?channelSetUuid={channelSetUuid}**

From the https://engdmzprism.portal.azure-api.net  portal while passing valid uuid , valid mnemonic and authentication code (with no body) it's saying 
400 Bad Request
Invalid request content while the "mnemonic": "ROP", and channelsetuuid “ee2642c4-baab-40dc-81dd-450e0e80dfca” is exist.

Am I doing something incorrect?

**Comment by niaalex** [comment]
@sukhendumukherjee  please notify client team of the block via slack.

**Comment by niaalex** [comment]
@sukhendumukherjee  please advise the status of the block now that the SLB team analysis is updated (below) 

@Sukhendu Mukherjee, we did find the 403 forbidden error from log system but failed to find the detailed information, we are enhancing the log for troubleshooting. Meantime, we had tried the requests and had successfully deleted channel set. We had also repeated the test by creating a new channel set and channels under it, then successfully deleted them. So, would you please try again? BTW, deleting a channel set will delete all data including channel under it, so you don't need to delete channel then.

**Comment by niaalex** [comment]
No longer blocked; @sukhendumukherjee last test and will be completed ETA 4/30

**Comment by TessForGithub2** [comment]
Coding is done; JUnit testing needs to start (ETA 5/1).

**Comment by niaalex** [comment]
Coding is done; Action is to open JUnit card and move to in progress.  JUNIT to begin 5/1.

**Comment by sukhendu555** [comment]
Need to add element delete.Currently we complete entire delete from object level.

**Comment by niaalex** [comment]
Reopened to capture additional scope

**Comment by sukhendu555** [comment]
Added initial code change for element delete.Will continue to work on testing through SOAP UI.

**Comment by sukhendumukherjee** [comment]
We have made changes for element delete and added code logic to take care 1411 and 1311 version.We are done with all rest calls and this card can be closed.
