### ISSUE TITLE
LOG: WMLS_UpdateInStore

### ISSUE THREAD

**Issue by sukhendumukherjee** [hashmapinc/Drillflow#395]
EPIC:
#361 Log CRUD Implementation
Sizing:
L (3-4Days)
Priority:
3. (UpdateStore must arrive at same time in order for GetFromStore to have something to work with)
Description: This is the "U" in "CRUD".
NOTES FROM MEETING WITH CHRIS:
-->Do not worry about caching
     *Redis--caching Wrapper for Traj--to prepare for caching
-->new channel add to channel set every 3 to 5 seconds
-->List:
     *never do the 1st one (never happens)
     *metadata replacement or append (1st priority - 3rd line)
     *channel data block clear
-->Do not go nuts with JUnit testing; only functionality & not the Java language
-->Do NOT put non-WITSML into the WITSML Library; always can use the Library, however..
4. Refer to:
This is the Swagger, and reveals the order in which things need to be done.

**Comment by niaalex** [comment]
@cherrera2001  see the original directive (above)  c/o UpdateToStore and advise of needed corrections.  There will be a one pager developed to document what was covered today (in the knowledge transfer) formally and archived for reference.

**Comment by TessForGithub2** [comment]
5/8 Started with the UpdateInStore Log request that accounts for 90% of the requests:
            POST - Add Channel data under a ChannelSet
       So far, I have created a Well, WellBore & Log to work with (I will delete when thru with them).
       I have placed a request straight from the WITSML API Guide into my Postman "[ChannelReader]
           [Update Flow] AppendData" XML request.

**Comment by TessForGithub2** [comment]
Closing this issue and will create separate cards for JUnit testing (this last time; in the future, I will be TDD and start with JUnit tests), and any support issues that arise from QA efforts.
