### ISSUE TITLE
QA:LOG:Finishing automation for Logs CRUD in SOAP UI

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#396]
Due to demo tomorrow for testing the basic functionality of Log CRUD Testcases, I am postponing this to next week.

**Comment by shehzadsidi** [comment]
Running into some formatting issue of SOAP XML in one test case.  I will to work on it.  This task is about 80% complete.

**Comment by shehzadsidi** [comment]
automated test cases done 90%.  There are couple of blocked items to be addressed.  (1) Full response xml payload needed to perform further groovy validations/asserts in Read Log GetFromStore.  (2) Delete Log DeleteFromStore test returns error, currently being worked at.

**Comment by TessForGithub2** [comment]
No change today due to block.

**Comment by shehzadsidi** [comment]
I was able to validate and put some asserts in automation for Logs GetFromStore for 2 elements in XMLOUT for ServiceCountry and indexType received back in response message.  More mappings in progress.

**Comment by shehzadsidi** [comment]
Just tested the DeleteFromStore and success!  AddToStore still requires more mappings which is in progress.  I have removed the block since both basic functionality works.

**Comment by niaalex** [comment]
Goof job!

**Comment by niaalex** [comment]
(oops) Good job :)

**Comment by TessForGithub2** [comment]
LOL

Awesome Shehzad! You came up to speed so quickly and are helping the DEV
team so much!

**Comment by niaalex** [comment]
This work is captured by other QA cards for LOG
