### ISSUE TITLE
Handoff for QA For #394 LOG: WMLS_DeleteFromStore 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#397]
Handoff for QA For #394 LOG: WMLS_DeleteFromStore 
EPIC:
#361 Log CRUD Implementation
Sizing:
L (3-4 Days)
Priority:
2
(DeleteFromStore must arrive at same time in order for GetFromStore to have something to work with)
Description:
This is the "D" in "CRUD".

**Comment by sukhendumukherjee** [comment]
Completed coding and testing and did the PR.PR approved and merged into master and deployed in QA.

**Comment by niaalex** [comment]
@sukhendumukherjee Is this card complete now?

**Comment by niaalex** [comment]
Handoff complete and SOAP UI test successful
