### ISSUE TITLE
QA: LOG: SoapUI Testing for WMLS_DeleteFromStore

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#399]
QA Testing Handoff for Dev Card 
#394 LOG: WMLS_DeleteFromStore 
and 
EPIC:  #361 Log CRUD Implementation

**Comment by shehzadsidi** [comment]
DeleteFromStore functionality not currently available.  It is being worked at by the development team

**Comment by TessForGithub2** [comment]
Completed the coding; verifying the data that you will hand off to QA is working. Once it is working, then I will hand off the Soap UI XML to QA. After handoff, I will begin JUnit Testing.

**Comment by niaalex** [comment]
Complete
