### ISSUE TITLE
LOG: QA SoapUI Testing for WMLS_UpdateToStore

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#400]
QA Testing Handoff for Dev Card

#395 LOG: WMLS_UpdateStore  and 

EPIC: #361 Log CRUD Implementation

**Comment by shehzadsidi** [comment]
There is an identified issue with SLB APIs for Logs.  SLB has been notified.  This impacts Add Logs (Log Data), Update Logs (Log Data), and Retrieve Logs (Log Data) test cases.

**Comment by shehzadsidi** [comment]
Test case Suite delivered for Drillflow release 0.13.0 for LOGS (Depth) supporting all CRUD functions.  I will open another sets of cards for the next major functionality- LOGS (Time).
