### ISSUE TITLE
DEV: LOG: JUnit Testing for WMLS_GetFromStore

### ISSUE THREAD

**Issue by sukhendumukherjee** [hashmapinc/Drillflow#401]
EPIC:
#361 Log CRUD Implementation
Sizing:
M (2-3 Days)
Priority:
3
(Junit Test for GetFromStore should completed after GetFromStore to have something to work with)
Description:
This is the "R" in "CRUD".

NOTE:
-->Do NOT put non-WITSML into the WITSML Library; always can use the Library, however..
4. Refer to:
https://engdmzprism.portal.azure-api.net/docs/services/democore-Slb-Prism-Core-Service-ChannelReader-4/operations/Channels_PostDepthBoundaryAsync
This is the Swagger, and reveals the order in which things need to be done.

**Comment by TessForGithub2** [comment]
We hammered out the interface between LogConverterExtended & GetFromStore; changes were required on both sides, so the JUnit testing will have to change.

**Comment by niaalex** [comment]
Pending review/ETA for close is EOD 5/2

**Comment by niaalex** [comment]
Reopened to capture additional scope.

**Comment by sukhendumukherjee** [comment]
Junit test cases added for GetFromStore and this card can be closed.
