### ISSUE TITLE
QA: Scripting: Verify GetFromStore (Groovy Scripting)

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#404]
The only requirement for data is that "What goes in must come out". So correct mappings are performed.

Hardcoding will be totally removed, and dynamic checks that the request fields are correctly portrayed in the response fields will be performed.

By COB on 4/26, at least 1 field will be verified. By COB on 4/29, all fields in a complete transaction will be verified.

**Comment by shehzadsidi** [comment]
Waiting on the full response payload for GetFromStore being currently worked at to further perform Groovy scripting validations/asserts

**Comment by TessForGithub2** [comment]
Still blocked.

**Comment by niaalex** [comment]
Pending channel assertions; channel sets with done.

**Comment by shehzadsidi** [comment]
I have automated most of the test cases and dynamically generating values.
