### ISSUE TITLE
DEV: Drillflow: Use CA Certificates 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#406]
This is the card to cover the client slack reply c/o Use CA Certificates.  Detail noted below: 

Shuping [3:13 AM]
Hi @Chris Herrera, required by SLB PaaS security standard, we have to use SLB CA issued certificate (instead of Self-Signed) to enable SSL for internal services (Well, Wellbore, Traj, Channel etc deployed in Service Fabric). As Drillflow connects to those back-end internal services and SLB CA is not in default trust store, so we need a new parameter injection to set CA to be used for Drillflow to validate certificates. The SLB CA is in PEM format which contains multiple lines of text, so the injected value will be in format: Base64Encoding(<raw text of SLB CA PEM file>). Any suggestion on this?

**Comment by TessForGithub2** [comment]
Reassigned to Sukhe since he will need this CA fix first.

**Comment by niaalex** [comment]
@sukhendumukherjee please advise the planned ETA for this item

**Comment by niaalex** [comment]
@sukhendumukherjee please classify/update this card where appropriate

**Comment by niaalex** [comment]
Closed by the client team/ Refer to email sent From: Shuping LIU <SLiu7@slb.com> 
Sent: Wednesday, August 21, 2019 5:37 AM
