### ISSUE TITLE
PM: Priority Qs for Issues

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#407]
After a little research on 
     https://github.com/features/project-management/
it is clear that there is no integrated priority mechanism for GitHub PM. I have found the following "ask" already in GitHub's awareness:

https://github.community/t5/How-to-use-Git-and-GitHub/Sort-Issues-by-Priority/m-p/5156?advanced=false&collapse_discussion=true&q=assigning%20priority&search_type=thread

There is a recommendation there as to how to use what we already have to somehow categorize our priorities. Shehzad has taken on the task of devising a mechanism for all of us to use.

I have also sent an email to the GitHub team so they are aware that yet another team would like this feature (and hopefully they will send me an update from the ask above).

**Comment by niaalex** [comment]
@TessForGithub2 @shehzadsidi if this will require programming by already engaged Dev resources this should be deferred to next sprint.  In the meantime we will address in the next call how we can better address any Priority Qs and a reasonable workflow for Issues.

**Comment by niaalex** [comment]
And we will manage this as a part of the retro and sprint planning.  I will assign myself for tracking.

**Comment by TessForGithub2** [comment]
I received a response from the GitHub folks:

_That's a great idea, but unfortunately It's not currently possible to do that. You can manually reorder issues in a column via drag and drop, alternatively you could have separate columns for different priorities._

So the 2018 comment that they might do this is a "scrub". They have no plans to provide priority.

We will manage the board simply & in a logical way. I have discussed on the QA & DEV team side, and we will create titles for cards as follows:

<Group>:<Functional Area>:<Class.Module as appropriate>:<Succinct & Correct Description>

Example:
DEV:LOG:LogConverter.convertToChannelSet:Enhance LogConverter to handle Log Data

**Comment by niaalex** [comment]
Noted

 

As I mentioned before we will proceed with the current BAU process and modify as needed. Thank you for the update.

**Comment by niaalex** [comment]
Item deferred/BAU strategy for now
