### ISSUE TITLE
DEV & QA:Max Data Nodes 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#408]
Per the client sprint plan - 
There is a Gap between certificate test case and current implementation (continue)
•	maxDataNodes/maxDataPoints/growingTimeoutPeriod injection
•	New API to support query trajectory & log data with maxDataNodes/maxDataPoints

HM will need to support this item. 

maxDataNodes/maxDataPoints/growingTimeoutPeriod injection (decided to add new API for trajectory & log, Prism will inject these configurations into Drillflow capabilities)

**Comment by niaalex** [comment]
@Mike-d-s please provide you input on this action item from last night so we can map accordingly.

**Comment by Mike-d-s** [comment]
These values are server parameters set by DrillOps based on their backend.  They are based on limits on their APIs for ingesting data.  We need to create the proper parameter injection for the DrillFlow container config to be able to add these to the GetCap server response.

**Comment by niaalex** [comment]
@shehzadsidi let me know if an Epic is needed for this or if a normal card for the parameter injection is sufficient.

**Comment by Mike-d-s** [comment]
This is not a test functionality.  This needs to be assigned to the dev team to add the necessary functionality to the DrillFlow and Valve configs so they can set these parameters during deployment of the container.

**Comment by Mike-d-s** [comment]
@niaalex Toni'a this needs to get broken out into different cards.  One for the actual implementation work to respect these parameters and one for the work needed to add these parameters into the configuration for the container and also to map them into the server GetCap.
