### ISSUE TITLE
Deserialize the well object

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#41]
Child of #33

After the AddToStore call is made, the well object needs to be Deserialized. Using the Hashmap Witsml Objects library: 

https://github.com/hashmapinc/WitsmlObjectsLibrary

We need to deserialize the object to be added depending on if it is 1.3.1.1 or 1.4.1.1

**Comment by randypitcherii** [comment]
Any chance you could provide some valid xml here for both the 1.3.1.1 case and the 1.4.1.1 case please?

**Comment by randypitcherii** [comment]
or point me to where I could find some

**Comment by randypitcherii** [comment]
Taking time to implement some new features in the WitsmlObjectsLibrary. BRB

**Comment by randypitcherii** [comment]
Nevermind, that repo would take a little time and effort to append to.

We're only going to support Well, WellBore, Trajectory, Log (depth and time); I'll just handle it in the Valve.
