### ISSUE TITLE
DEV: LOG: JUnit Testing for WMLS_DeleteFromStore

### ISSUE THREAD

**Issue by sukhendumukherjee** [hashmapinc/Drillflow#412]
EPIC:
#361 Log CRUD Implementation
Sizing:
M (2-3 Days)
Priority:
3
(Junit Test for DeleteFromStore should completed after DeleteFromStore to have something to work with)
Description:
This is the "D" in "CRUD".

NOTE:
-->Do NOT put non-WITSML into the WITSML Library; always can use the Library, however..
4. Refer to:
https://engdmzprism.portal.azure-api.net/docs/services/democore-Slb-Prism-Core-Service-ChannelReader-4/operations/Channels_PostDepthBoundaryAsync
This is the Swagger, and reveals the order in which things need to be done.

**Comment by niaalex** [comment]
On target for 5/2 Close

**Comment by niaalex** [comment]
Pending review / ETA for closure EOD 5/2

**Comment by niaalex** [comment]
@sukhendumukherjee what is the ETA for this one closing?

**Comment by sukhendu555** [comment]
Added code for Junit Test case for Delete from store.
Will be working on to write Junit test case for element delete.Once Element delete functionality do work Junit will be done same time.ETA 05/15.

**Comment by sukhendumukherjee** [comment]
JUnit test cases added for DeleteFromStore and it can be closed.
