### ISSUE TITLE
Return for requestObjectSelectionCapability wells element attributes needs space between attributes.

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#417]
Objectselection return now contains correct elements, but I'm having trouble getting the return to parse in the SoapUI test using xmlSlurper.  Return currently is:
```
<wells xmlns="http://www.witsml.org/schemas/1series"version="1.4.1.1">
	<well uid="uid_dfTestWell1">
	<name>dfTestWell1</name>
	<numGovt>12345</numGovt>
	<numAPI>12345</numAPI>
		<commonData>
			<dTimLastChange>2019-03-08T19:47:27.545Z</dTimLastChange>
		</commonData>
	</well>
</wells>
```
Parse error reports an expected > or /> when processing the wells element attributes.  Currently the attributes read as:

wells xmlns="http://www.witsml.org/schemas/1series"version="1.4.1.1"

I think a space is required between the namespace and the version.  So the expected is:

wells xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1"

_Originally posted by @Mike-d-s in https://github.com/hashmapinc/Drillflow/issues/373#issuecomment-489423014_

**Comment by niaalex** [comment]
This will be evaluated for next sprint

**Comment by Mike-d-s** [comment]
#692
