### ISSUE TITLE
Log Curve info not returning min/max index

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#447]
Currently the log curve info is not returning the min and max index from the returned data range. This needs to come from the data that is being returned and put into the log curve info when requested.

**Comment by sukhendumukherjee** [comment]
There are two scenarios

1. For Depth data
   I have fixed code for depth data where max and min index are showing.

2. For Time data
 we should add minDateTimeIndex and maxDateTimeIndex under logCurveInfo to test it.
We are working to make sure its adding in store first then can test these two elements.

**Comment by sukhendumukherjee** [comment]
Its working as expected.
