### ISSUE TITLE
DEV:LOG:Log Curve Info not returning min max for metadata query only

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#448]
When there is a metadata only query (no logData) does not return min max index. This actually needs to come from another set of api's  

https://base-url/democore/channelreader/v4/channels/timeboundary

and 

https://base-url/democore/channelreader/v4/channels/depthboundary respectively

**Comment by sukhendumukherjee** [comment]
Fixed.Will deploy after Demo Done.

**Comment by niaalex** [comment]
Pending further Min/Max Data review/  New ETA is 6/17 update by 3pm @sukhendumukherjee

**Comment by niaalex** [comment]
DEV/Test teams will collaborate on this item
