### ISSUE TITLE
DEV:LOG:A double query for log is not returning correctly

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#449]
Currently for the query 

``` xml
<logs xsi:schemaLocation="http://www.witsml.org/schemas/1series http://www.witsml.org/schemas/1series/obj_log.xsd" version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
  <log uidWell="HM_a0096e5b-27e8-4240-a4ba-1fb3256c86d2" uidWellbore="HM_da71e0a7-6276-4874-9742-c21ce3f3b1b2" uid="HM_713a6c33-5634-40aa-9eea-36696c9babd8"> 
    <nameWell /> 
    <nameWellbore /> 
    <name /> 
    <objectGrowing /> 
    <serviceCompany /> 
    <runNumber /> 
    <pass /> 
    <bhaRunNumber /> 
    <indexType /> 
    <startIndex /> 
    <endIndex /> 
    <startDateTimeIndex /> 
    <endDateTimeIndex /> 
    <direction /> 
    <indexCurve /> 
    <nullValue /> 
    <logCurveInfo uid=""> 
      <mnemonic /> 
      <unit /> 
      <nullValue /> 
      <minIndex uom="" /> 
      <maxIndex uom="" /> 
      <minDateTimeIndex /> 
      <maxDateTimeIndex /> 
      <curveDescription /> 
      <typeLogData /> 
      <axisDefinition /> 
    </logCurveInfo> 
  </log> 
  <log uidWell="HM_a0096e5b-27e8-4240-a4ba-1fb3256c86d2" uidWellbore="HM_da71e0a7-6276-4874-9742-c21ce3f3b1b2" uid="L-12345-log"> 
    <nameWell /> 
    <nameWellbore /> 
    <name /> 
    <objectGrowing /> 
    <serviceCompany /> 
    <runNumber /> 
    <pass /> 
    <bhaRunNumber /> 
    <indexType /> 
    <startIndex /> 
    <endIndex /> 
    <startDateTimeIndex /> 
    <endDateTimeIndex /> 
    <direction /> 
    <indexCurve /> 
    <nullValue /> 
    <logCurveInfo uid=""> 
      <mnemonic /> 
      <unit /> 
      <nullValue /> 
      <minIndex uom="" /> 
      <maxIndex uom="" /> 
      <minDateTimeIndex /> 
      <maxDateTimeIndex /> 
      <curveDescription /> 
      <typeLogData /> 
      <axisDefinition /> 
    </logCurveInfo> 
  </log> 
</logs>
```

The result is not returning correctly, it returns as:

```xml
<logs xsi:schemaLocation="http://www.witsml.org/schemas/131 http://www.witsml.org/schemas/131/obj_log.xsd" version="1.3.1.1" xmlns="http://www.witsml.org/schemas/131" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
  <log uid="HM_713a6c33-5634-40aa-9eea-36696c9babd8"> 
    <nameWell>Well HM_a0096e5b-27e8-4240-a4ba-1fb3256c86d2</nameWell> 
    <nameWellbore>HM_da71e0a7-6276-4874-9742-c21ce3f3b1b2</nameWellbore> 
    <name>HM_713a6c33-5634-40aa-9eea-36696c9babd8</name> 
    <serviceCompany>Baker Hughes INTEQ</serviceCompany> 
    <runNumber>12.3</runNumber> 
    <indexType>time</indexType> 
    <indexCurve columnIndex="0">Time</indexCurve> 
    <nullValue>-999.25</nullValue> 
    <logCurveInfo uid=""> 
      <mnemonic /> 
      <unit /> 
      <nullValue /> 
      <minIndex uom="" /> 
      <maxIndex uom="" /> 
      <columnIndex></columnIndex> 
      <curveDescription /> 
      <typeLogData /> 
      <axisDefinition> 
        <order>0</order> 
        <count>0</count> 
        <doubleValues /> 
        <stringValues /> 
      </axisDefinition> 
    </logCurveInfo> 
  </log> 
  <log uid="L-12345-log"> 
    <nameWell>Well HM_a0096e5b-27e8-4240-a4ba-1fb3256c86d2</nameWell> 
    <nameWellbore>HM_da71e0a7-6276-4874-9742-c21ce3f3b1b2</nameWellbore> 
    <name>Log ABC-MD</name> 
    <indexType>depth</indexType> 
    <startIndex uom="m">1000.0</startIndex> 
    <endIndex uom="m">1018.0</endIndex> 
    <indexCurve columnIndex="0">Depth</indexCurve> 
    <logCurveInfo uid=""> 
      <mnemonic /> 
      <unit /> 
      <nullValue /> 
      <minIndex uom="" /> 
      <maxIndex uom="" /> 
      <columnIndex></columnIndex> 
      <curveDescription /> 
      <typeLogData /> 
      <axisDefinition> 
        <order>0</order> 
        <count>0</count> 
        <doubleValues /> 
        <stringValues /> 
      </axisDefinition> 
    </logCurveInfo> 
  </log> 
</logs> 
```

which is missing all of the log curve info. I suspect something is happening in the merge...but it needs to be investigated.

**Comment by sukhendumukherjee** [comment]
Its working well.I tested with following set of data and getting all channels back.

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://www.witsml.org/wsdl/120" xmlns:types="http://www.witsml.org/wsdl/120/encodedTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
     <q1:WMLS_GetFromStore xmlns:q1="http://www.witsml.org/message/120">
        <WMLtypeIn xsi:type="xsd:string">log</WMLtypeIn>
        <QueryIn xsi:type="xsd:string"><![CDATA[<logs xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1">
     <log uidWell="Energistics-well-0001" uidWellbore="Energistics-w1-wellbore-0001" uid="HM_f8aebaa1-b998-4ceb-ae65-b2d8af4761dg">
        <nameWell>Well Energistics-well-0001</nameWell>
        <nameWellbore>Wellbore Energistics-w1-wellbore-0001</nameWellbore>
        <name>Log_HM_f8aebaa1-b998-4ceb-ae65-b2d8af4761de</name>
    <objectGrowing /> 
    <serviceCompany /> 
    <runNumber /> 
    <pass /> 
    <bhaRunNumber /> 
    <indexType /> 
    <startIndex /> 
    <endIndex /> 
    <startDateTimeIndex /> 
    <endDateTimeIndex /> 
    <direction /> 
    <indexCurve /> 
    <nullValue /> 
    <logCurveInfo uid=""> 
      <mnemonic /> 
      <unit /> 
      <nullValue /> 
      <minIndex uom="" /> 
      <maxIndex uom="" /> 
      <minDateTimeIndex /> 
      <maxDateTimeIndex /> 
      <curveDescription /> 
      <typeLogData /> 
      <axisDefinition /> 
    </logCurveInfo> 
  </log> 
  <log uidWell="Energistics-well-0001" uidWellbore="Energistics-w1-wellbore-0001" uid="HM_f8aebaa1-b998-4ceb-ae65-b2d8af4761df">
        <nameWell>Well Energistics-well-0001</nameWell>
        <nameWellbore>Wellbore Energistics-w1-wellbore-0001</nameWellbore>
        <name>Log_HM_f8aebaa1-b998-4ceb-ae65-b2d8af4761de</name>
    <objectGrowing /> 
    <serviceCompany /> 
    <runNumber /> 
    <pass /> 
    <bhaRunNumber /> 
    <indexType /> 
    <startIndex /> 
    <endIndex /> 
    <startDateTimeIndex /> 
    <endDateTimeIndex /> 
    <direction /> 
    <indexCurve /> 
    <nullValue /> 
    <logCurveInfo uid=""> 
      <mnemonic /> 
      <unit /> 
      <nullValue /> 
      <minIndex uom="" /> 
      <maxIndex uom="" /> 
      <minDateTimeIndex /> 
      <maxDateTimeIndex /> 
      <curveDescription /> 
      <typeLogData /> 
      <axisDefinition /> 
    </logCurveInfo> 
  </log> 
</logs>]]></QueryIn>
        <OptionsIn xsi:type="xsd:string"></OptionsIn>
        <CapabilitiesIn xsi:type="xsd:string"/>
     </q1:WMLS_GetFromStore>
  </soap:Body>
</soap:Envelope>

**Comment by niaalex** [comment]
This item will go in the PR today/ ETA 6/17 3pm @sukhendumukherjee

**Comment by sukhendumukherjee** [comment]
Working in DEV need to test in QA
