### ISSUE TITLE
DEV:LOG:Modify the convertChannelDepthDataToDotFrom to include start and end index filters

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#451]
Size: 
Medium

Currently the data query only takes into account name, but not start or end index. This needs to be taken into account, when these values are passed in. Either from the logCurveInfo or the overall log min/max.

**Comment by sukhendumukherjee** [comment]
Fixed and working well.Will be tested in QA after Demo.

**Comment by niaalex** [comment]
This item will go with the PR today.  ETA 6/16.  @sukhendumukherjee

**Comment by sukhendumukherjee** [comment]
Need to Tested.
