### ISSUE TITLE
DEV:LOG: AddToStore minDateTimeIndex and maxDateTimeIndex (Maintenance: TIME) 

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#458]
This card supports #447 as discovered during QA Testing.

In both v1311 and v1411, for a time log, we will have minDateTimeIndex and maxDateTimeIndex under logCurveInfo. This has not been provided by AddToStore.

This blocks #447 until a valid test scenario can be provided to progress testing on that card.

**Comment by Mike-d-s** [comment]
EPIC:
#361 Log CRUD Implementation

**Comment by niaalex** [comment]
Dev sync required. New ETA TBD. @TessForGithub2

**Comment by TessForGithub2** [comment]
UPDATE: Put in the fix and Shehzad reports it is working. However, he has 1 minor issue so wants the card to remain open.

**Comment by niaalex** [comment]
@shehzadsidi  confirmed this is complete. Delivered with 0.16.0.
