### ISSUE TITLE
Well GetFromStore

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#46]
Requires #43
Child of #101

This card will build on the work in #43 and add the delegation for GetFromStore.

**Comment by randypitcherii** [comment]
@cherrera2001 will you please provide a 1K foot strategy for sucking this information out of the drilltest api?

More specifically:
- Which pieces of data are needed from the drilltest api to construct the object in a Witsml2 `Well` object
- How many / which queries should be sent (1 query + regex? Spring rest calls?)

Thanks!

**Comment by randypitcherii** [comment]
My "plan A" is to use https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fluent.html and just parse the body response as a string

**Comment by randypitcherii** [comment]
General strategy is:
- Store gets request and constructs a QueryContext
- Store sends QueryContext to the Valve
- The DoT Valve Delegator enriches the QueryContext with a REST query plan, executes the REST calls, and sends the results the DotTranslator
- The DotTranslator converts the rest response data into the proper Witsml2 POJO based on the object type (log, traj, well, wellbore).
- The DotTranslator then uses the QueryContext to get the expected version and uses the WitsmlObjectsLibrary to translate the 2.0 object to the proper version
- The properly versioned object is then serialized into an XML string and returned to the DotDelegator
- The DotDelegator returns the string to the valve
- the valve returns the string to the Store
- The store returns the string to SPRING which does black magic to respond to the client in the expected SOAP format

I will create sub cards for some of this functionality

**Comment by randypitcherii** [comment]
@cherrera2001 at your convenience, please see #89 #91 and #92 to see the detailed cards created to accomplish well `getFromStore` functionality.

This will lay the groundwork in a major way for how `getFromStore` works for `wellbore`, `log`, and `trajectory` as well.

**Comment by randypitcherii** [comment]
@cherrera2001 and @vijaypoojari 

See the updated strategy for `getFromStore`:

![image](https://user-images.githubusercontent.com/8570256/49031508-be3af980-f16f-11e8-9f83-99b275001ae5.png)

**Comment by randypitcherii** [comment]
## NOTE: regarding the translation process | DoT Translator Design

### XML Query string to JSON object
- Populated = filters for queries
- Unpopulated = values to query for


### JSON object to XML query response string
- Use the WitsmlObjects library to convert JSON to POJO
- Convert POJO from 1.4.1.1 to 1.3.1.1 if QueryContext says so using built-in functionality of the WitsmlObjects library
- Serialize to xml string using WitsmlObjects library

**Comment by randypitcherii** [comment]
### NOTE: Cool translation development
Chris's fantastic `WitsmlObjects` library helps us so much.

The general flow for conversion is now:
- Use `WitsmlObjects` to parse the input `version` and `queryXML` into a POJO
- Convert the pojo to a JSON 1.4.1.1 object
- Execute REST calls to populate empty json fields
- Convert filled json back to 1.4.1.1 POJO
- Convert POJO to proper version (1.4.1.1 or 1.3.1.1)
- Use the `WitsmlObjects` library to serialize the POJO to string

**Comment by randypitcherii** [comment]
See Chris's excellent GIST on JSON usage in `WitsmlObjects` library here:

https://gist.github.com/cherrera2001/d39b944640de1202d91ac1a9203d525c
