### ISSUE TITLE
DEV:LOG: get from store does not return commonData

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#471]
Epic
#361  Log CRUD implementation
Size: 
Medium

Bug:
Perform the following query for a log.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<logs xmlns="http://www.witsml.org/schemas/1series" 	
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.witsml.org/schemas/1series  ../xsd_schemas/obj_log.xsd" 
	version="1.4.1.1">
	<log uidWell="Energistics-Well-0001" uidWellbore="Energistics-w1-wellbore-0001" uid="Test_depth_log2">
		<nameWell></nameWell>
		<nameWellbore></nameWellbore>
		<name></name>
		<commonData>
			<dTimCreation></dTimCreation>
			<dTimLastChange></dTimLastChange>
			<itemState></itemState>
			<comments></comments>
		</commonData>
	</log>
</logs>
```
Server return does not include commonData as requested , though common data was included when the log was created. 

Return:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<logs version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series"
	xmlns:ns2="http://www.energistics.org/schemas/abstract">
<log uid="Test_depth_log2">
<nameWell>Well Energistics-well-0001</nameWell>
<nameWellbore>Wellbore Energistics-w1-wellbore-0001</nameWellbore>
<name>Test_depth_log2</name>
</log>
</logs>
```

Expected result:
commonData should have been returned

**Comment by sukhendumukherjee** [comment]
When we added common data from AddToStore as below 
  	       <commonData>
			<dTimCreation>2003-11-24T08:15:00.000Z</dTimCreation>
			<dTimLastChange>2003-11-24T08:15:00.000Z</dTimLastChange>
			<itemState>plan</itemState>
			<comments>These are the comments associated with the log object.</comments>
		</commonData>

We see response from DOT having itemState and comments.Not getting dTimCreation and dTimLastChange.From where we will get these values ?

**Comment by niaalex** [comment]
The PR for this one will be done today.  @sukhendumukherjee  will update this today.  New ETA TBD

**Comment by sukhendumukherjee** [comment]
Currently we are getting itemState , dTimCreation fand comments rom DOT and now it’s added in common data.We are not getting dTimLastChange
from DOT and I have created a card df-517  to address that.
