### ISSUE TITLE
DEV:LOG:Testing with a v1.3.1.1 request and get Unhandled error from REST backend.

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#486]
EPIC:
#361 Log CRUD Implementation
Size:
Medium

While putting in the change for columnIndex for v1.3.1.1 Response, I received this error. I verified that columnIndex now has the correct value (instead of just assigning classIndex to columnIndex), so this appears to be a new error. I may just have to pick up Sukhe's fixes to correct this.

**Comment by TessForGithub2** [comment]
I will create a new branch with this number to check what is in Master. Then I will add my fixes to see where the error is coming from.

**Comment by niaalex** [comment]
This item will be retested by the dev team today to verify the fix.  ETA is 3pm 6/17.

**Comment by TessForGithub2** [comment]
UPDATE: Retest. Not seeing it now.

**Comment by niaalex** [comment]
@TessForGithub2  will address with 1311 - ETA is 7/19

**Comment by niaalex** [comment]
@sukhendumukherjee  will look into this item and update by 7/29

**Comment by TessForGithub2** [comment]
UPDATE: Leaving this open to make sure we fixed this.
