### ISSUE TITLE
Duplicate Env Keys

### ISSUE THREAD

**Issue by sukhendumukherjee** [hashmapinc/Drillflow#487]
This Defect to address duplicate env keys

Shuping [1:20 AM]
@Theresa Stewart, we are trying to run image 0.13.0 and as the https://drillflow.readthedocs.io/en/latest/integration/dot/envvars.html does not have the documentation for log related env settings, so I refer to https://github.com/hashmapinc/Drillflow/blob/master/df-server/src/main/resources/application.yml and have found below - there are 2 occurrences of  duplicated environment keys which results in no way to inject `log.channel.path` and `log.channels.data.path`.  BTW, is the `/:mnemonic` one correct in injection? should we keep the same style when injecting?

       log.channelset.path: ${*LOG_PATH*:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channelSets}
       log.channel.path: ${*LOG_PATH*:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels}
       log.channelset.metadata.path: ${LOG_CHANNELSET_METADATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channelSets}
       log.channelset.uuid.path: ${LOG_CHANNELSET_UUID:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/identities}
       log.channels.path: ${*LOG_CHANNELS*:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/metadata}
       log.channels.data.path: ${*LOG_CHANNELS*:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/data}
       log.mnemonic.data.path: ${LOG_MNEMONIC:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/:mnemonic}
       log.channel.depthData.path: ${LOG_DEPTHDATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/depthdata}
       log.channel.timeData.path: ${LOG_TIMEDATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/timedata}
       log.channelset.search: ${LOG_SEARCH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channelSets} (edited)

**Comment by TessForGithub2** [comment]
EPIC:
#361 Log CRUD Implementation

**Comment by sukhendumukherjee** [comment]
Duplicate Env Key fixed and deployed.

        log.channelset.path: ${LOG_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channelSets}
        log.channel.path: ${LOG_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels}
        log.channelset.uuid.path: ${LOG_CHANNELSET_UUID:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/identities}
        log.channels.path: ${LOG_CHANNELS:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/metadata}
        log.channels.data.path: ${LOG_CHANNELS:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/data}
        log.mnemonic.data.path: ${LOG_MNEMONIC:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/:mnemonic}
        log.channel.depthData.path: ${LOG_DEPTHDATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/depthdata}
        log.channel.timeData.path: ${LOG_TIMEDATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/timedata}
        log.channel.depthBoundaryData.path: ${LOG_DEPTH_BOUNDARY_DATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/depthboundary}
        log.channel.timeBoundaryData.path: ${LOG_TIME_BOUNDARY_DATA:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/timeboundary}
