### ISSUE TITLE
Create tests cases for GetFromStore for well

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#49]
Child of #47
Create test cases for GetFromStore.

It should test:

GetMultipleWells
GetSingleWell
Sending in Garbage information
Sending empty requests

**Comment by randypitcherii** [comment]
I've set up test structure, but we should discuss expected inputs / outputs as well as the test strategy (how to add objects to the store in the test??)

**Comment by randypitcherii** [comment]
Nevermind, I'll undo my changes and leave this. Sorry, Billy

**Comment by randypitcherii** [comment]
@cherrera2001 @bbuckles  who's working on this? Billy, are you doing this?

I'm happy to do it, but last I heard from Chris, this task was meant for Billy.

Thanks!

**Comment by randypitcherii** [comment]
@niaalex FYI as well. This has been on the board for a few weeks with no action. Want to make sure we're not overlooking it

**Comment by bbuckles** [comment]
Test scripting is complete for Get From Store Well.
