### ISSUE TITLE
DEV:FsR: GET (R) Fluids Report Object

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#492]
EPIC: 
#491 Fluid Report Implementation 
Size: 
TBD Pending 6/12 LOE review 

DEV: GET (R) Fluids Report Object Identity  and  GET (R) Fluids Report by UUID

**Comment by TessForGithub2** [comment]
Update: Sukhe ETA 7/24

**Comment by sukhendumukherjee** [comment]
Dev Complete
