### ISSUE TITLE
DEV:FsR: AddToStore

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#493]
EPIC: 
#491 Fluid Report Implementation
Size: 
TBD Pending LOE review on 6/12

DEV: ADD (C) Fluids Report Object Identity and DEV: ADD (C) Fluids Report by UUID
DEV: Add FluidsReport to the GetCap server response.

**Comment by TessForGithub2** [comment]
Update: Theresa is working on this now and ETA is 7/24

**Comment by TessForGithub2** [comment]
Update: Delivered in container 0.17.0 for 1.4.1.1 but will test for 1.3.1.1.

**Comment by TessForGithub2** [comment]
Update: Will test for 1.3.1.1 and verify for 1.4.1.1 the fix for getting all elements of a complete Fluids Report object.

**Comment by TessForGithub2** [comment]
Update: Essentially Add is working for the test cases provided. However, I still need to test for 1.3.1.1 and understand why I am seeing 500 error (still popping up).
