### ISSUE TITLE
DEV: UPDATE (U) Fluids Report Object 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#494]
EPIC: 
#491  - Fluid Report Implementation

SIZE: 
TBD pending 6/12 LOE review 

DEV: UPDATE (U) Fluids Report Object

**Comment by TessForGithub2** [comment]
Update: Theresa has provided access to the object with the WitsmlObjectsLibrary. She will complete Update ETA 7/25

**Comment by TessForGithub2** [comment]
Update: UpdateToStore is now failing in getUUIDFR (throw new ValveException(“No fluids report date found.“);)

Requested a trace from Sukhe.

**Comment by TessForGithub2** [comment]
Update: UpdateToStore is now working. Will complete testing this morning with Shehzad and plan to release for Container 0.17.1 8/7.
