### ISSUE TITLE
DEV:FsR: DELETE (D) Fluids Report Object

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#495]
EPIC:
#491 Fluid Report Implementation
Size:
TBD Pending 6/12 LOE review

DEV: DELETE (D) Fluids Report Object

**Comment by TessForGithub2** [comment]
Update: Sukhe is working on this and his ETA is 7/25

**Comment by sukhendumukherjee** [comment]
Development Complete
