### ISSUE TITLE
DEV:FsR: Query 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#496]
EPIC: 
#491 Fluid Report Implementation 

SIZE: 
TBD Pending 6/12 LOE Review 

DEV: Fluid Report Object Query / Graph QL for the fluids report conversion

**Comment by niaalex** [comment]
@sukhendumukherjee Please advise the status on this activity and provide an update on your action to confirm Script availability and verification of the Fluids Report API from portal.

Note SLB request to add Adrien Chassard <AChassard@slb.com> to the thread for all Fluids Report updates.

**Comment by TessForGithub2** [comment]
Update: Sukhe's ETA is 7/24

**Comment by niaalex** [comment]
@sukhendumukherjee will confirm if this is still valid.
ETA - 7/25

**Comment by sukhendumukherjee** [comment]
We are not using graph ql.
