### ISSUE TITLE
DEV:LOGS:ENV Variables Setup Documentation (HIGH PRIORITY)

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#498]
EPIC:
#361 Log CRUD Implementation
Card Size:
Small

environment variables setup documentation on readthedocs seems to be out of date compared to the current container config.  We need to update this it looks like.  If they were trying to build from the docs it would have appeared out of sync

Task also includes updating process so that changes to the container configuration is also updated in the readthedocs.io documentation.

**Comment by Mike-d-s** [comment]
Card sizing:
Small

**Comment by TessForGithub2** [comment]
UPDATE: Performed the edit on GitHub.

**Comment by TessForGithub2** [comment]
UPDATE: card also involves changing the documentation already presented due to removing a baseURL and requiring a full URL be provided by the client. Also, the URL used in this public documentation needed to be obfuscated but yet relevant enough that the client can see the pattern.

**Comment by TessForGithub2** [comment]
UPDATE: Changes are in envvars.rst in df-510. Pull request created & just waiting Sukhe's review #556

**Comment by niaalex** [comment]
This item has been reviewed and released.  No issues/close.
