### ISSUE TITLE
QA: Log Curve Info not returning min max for metadata query only (Linked Card #448)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#504]
Test to ensure that Log Curve info contains min and max for metadata only query (Linked Card #448)

**Comment by niaalex** [comment]
Further discussion in progress and dependent on several scenarios.  New ETA is TBD this item will be deferred to next sprint.

**Comment by shehzadsidi** [comment]
Min and Max index in both Logs (Depth and Time) are tested successfully in QA.  Closing the card.
