### ISSUE TITLE
DEV: QA: Add To Store Logs (1.4.1.1 and 1.3.1.1) with Channel Sets Only returns null error (HIGH PRIORITY)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#505]
Adding Log Object with Channel Sets ONLY results in error: Error adding to store: null.

**Comment by niaalex** [comment]
The Code Fix submitted.  New Error in review as High Priority.  New ETA is 6/17.

**Comment by niaalex** [comment]
Dev what is the update on this one?

**Comment by TessForGithub2** [comment]
UPDATE: Releasing the fix now. The problem is that Channel Sets needs Channels for UOM. Now the code will return the correct error response.

**Comment by TessForGithub2** [comment]
UPDATE: Released under branch df-551 (PR #592).
