### ISSUE TITLE
QA:LOGS: Revise test cases for change to indexType to enumerated value

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#508]
Epic:
#361 
Size:
Small

Log Sanity testing validations to be updated to check for the schema compliant enumerated values for get from store for indexType.

Previously we mapped from measured depth to Depth and date time to Time for DOT.  Now DOT has changed to use the schema compliant enumerated values and we need to update our validations in the test cases.  

The new DOT implementation uses 'measured depth' and 'date time' as the values.

**Comment by niaalex** [comment]
@shehzadsidi will refresh this card today.  ETA 6/17

**Comment by shehzadsidi** [comment]
New Index Type ("measured depth" and "date time") successfully tested.
