### ISSUE TITLE
DEV:LOGS: Update indexType check and switch to use new enumerated values

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#511]
Epic:
#361 
Size: 
Small

The DOT team has updated their values for indexType from "Time" and "Depth" to use the schema compliant enumerated values of "date time" and "measured depth".

We need to update the getFromStore query switch for the index type processing to check for the new enumerated value instead of the previous values.

**Comment by TessForGithub2** [comment]
UPDATE: Sukhe closed this 6/12
