### ISSUE TITLE
DEV: FsR: Create the POJO 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#512]
EPIC: 
#491 Fluids Report Implementation 
PARENT: 
#493 Add to Store (C) Fluids Report Object 
SIZE: 
8 hours = 1 day = 2 points 
 
Create the POJO – Time Med is 8 hours (full day)

**Comment by TessForGithub2** [comment]
Update: POJOs for all versions (1.3.1.1, 1.4.1.1, and 2.0) have been created in the WitsmlObjectLibrary.
