### ISSUE TITLE
DEV: FsR: Marshaling to POJO

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#513]
EPIC: 
#491 Fluids Report Implementation 
PARENT: 
#493 Add to Store (C) Fluids Report Object 
SIZE: 
4 hours = 1/2 day = 1 point 

DEV: Fluids Report: Marshalling to POJO

**Comment by TessForGithub2** [comment]
Update: Theresa is currently working on this with AddToStore:FsR.

ETA: 7/24.

**Comment by TessForGithub2** [comment]
Update: All objects are receiving POJO data. Closing this card now.
