### ISSUE TITLE
DEV: Fluid Reports: Mapping - Ingesting the Mapping 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#514]
EPIC: 
#491 Fluids Report Implementation 
PARENT: 
#493 Add to Store (C) Fluids Report Object 
SIZE: 
4 hours = 1/2 day = 1 point (confirm size with TS)

Ingestion Mapping for ADD to Store

**Comment by TessForGithub2** [comment]
Update: All CRUD Objects will ingest the mapping. Since this is inherent in the objects' design, I will close this card as "understood that this is happening this week, and as each CRUD object closes, it will be done."
