### ISSUE TITLE
DEV: FsR: Mappings

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#515]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point (confirm size with TS)

Development for Mapping  for ADD to Store

**Comment by TessForGithub2** [comment]
UPDATE: The converter with the mappings has been completed after review by Chris. There will not be an extended converter, so the following is true:
1.3.1.1 -> 2.0, 2.0 -> 1.3.1.1 is done
1.4.1.1 -> 2.0, 2.0 -> 1.4.1.1 is done
no effort for 2.0 -> 2.0 is required (obvious but worth mentioning)

**Comment by TessForGithub2** [comment]
Update: There was some missing data that has now been provided by the Mapping software. To my knowledge, all required elements are there so I am closing this card.
