### ISSUE TITLE
QA: FsR: AddToStore with Same UID

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#516]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point  (small)

Testing/QA: Fluids Report: Activity Test POST with Same UID – Size Small (1pt)

**Comment by TessForGithub2** [comment]
Update: Special case, deferred in priority until after Happy Path & Sanity Tests.

**Comment by shehzadsidi** [comment]
While attempting to perform AddToStore with same UID, I receive error as expected:
For example: <SuppMsgOut>{"message":"Key conflicts, duplicate wellboreId+uid, wellboreId=0e2e84f9-0b5d-402e-8d3c-ae6f3e8f8b63, uid=HM_86990ca8-d77e-48bb-ac93-22846e05f316"}</SuppMsgOut>.  Closing the card
