### ISSUE TITLE
DEV:LOG:DOT is not returning  dTimLastChange for commonData

### ISSUE THREAD

**Issue by sukhendumukherjee** [hashmapinc/Drillflow#517]
DOT is not returning back dTimLastChange for commonData.

<commonData>
			<dTimCreation></dTimCreation>
			<dTimLastChange></dTimLastChange>
			<itemState></itemState>
			<comments></comments>
</commonData>

**Comment by sukhendumukherjee** [comment]
Currently we are getting itemState , dTimCreation and comments from DOT and now it’s added in common data and deployed in QA.We are not getting dTimLastChange.SLB need to confirm about dTimLastChange.

**Comment by TessForGithub2** [comment]
Update: Sukhe confirmed this is done.
