### ISSUE TITLE
DEV: FsR: AddToStore with or without UID 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#518]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
8 hours = 1 day = 2 points

DEV: Fluids Report: ADD POST with or without UID – Size (2pts)

**Comment by TessForGithub2** [comment]
Update: This will be done at the same time as AddToStore Happy Path & Sanity cases (it is a by-product of creating the code for AddToStore). I will leave this card open, however, as a reminder of these development use cases.

**Comment by TessForGithub2** [comment]
Update: The code has been provided for both with/without UID. I need to retest, however, without UID since I was seeing a 500 from the client & need to verify that this has been rectified.

**Comment by TessForGithub2** [comment]
Update: When I remove the uid from the transaction, DoT fails it as follows:
Payload: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns1:WMLS_AddToStoreResponse xmlns:ns1="http://www.witsml.org/message/120"><Result xmlns:ns2="http://www.witsml.org/wsdl/120"><Result>-1</Result><SuppMsgOut>{"message":"The request is invalid.","modelState":{"uid.String":["A value is required but was not present in the request."]}}</SuppMsgOut></Result></ns1:WMLS_AddToStoreResponse></soap:Body></soap:Envelope>

I have an ask out to XiaoBin DENG for Use Case clarification.

**Comment by TessForGithub2** [comment]
Update: Worked with XiaoBen DENG and now it works. He did not change anything on DoT side and I did not on DrillFlow side, so it is a mystery as to why the previous time failed. However, I've run it 3 more times now, and it is working. I left XiaoBen with a JSON payload to examine. But I will close this card now.

@Shehzad can now test it.
