### ISSUE TITLE
QA: FsR:AddToStore  

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#521]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
8 hours = 1 day = 2 points

QA: Fluids Report: Add to Store for New Object Test Cases – Size (2pts)

**Comment by TessForGithub2** [comment]
Update: Shehzad has started this effort; ETA: 7/24

This will be a full object test, vanilla sanity test for 1.4.1.1

**Comment by TessForGithub2** [comment]
Update: This Happy Path & Sanity for 1.4.1.1 has been provided.
