### ISSUE TITLE
QA: FsR: ADD POST with UID 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#522]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point

QA: Fluids Report: ADD POST with UID – Size (1 pt)

**Comment by niaalex** [comment]
@shehzadsidi what is the current status on this item including the planned ETA?

**Comment by shehzadsidi** [comment]
AddToStore for elements including "Rheometer" need to be tested for container 0.17.1.  ETA 8/5 (COB)

**Comment by shehzadsidi** [comment]
AddToStore for elements including "Rheometer" need to be tested for container 0.17.1. ETA 8/7 (COB)

**Comment by TessForGithub2** [comment]
UPDATE: We are keeping this card open due to fields that are lost during the marshal process (hardnessCa) or due to missing schema location (ASG). Once these fields are resolved, we need to test again.

**Comment by shehzadsidi** [comment]
Rheometer issue fixed and QA tested.  The other missing fields already has an assigned card.  Closing the card.
