### ISSUE TITLE
QA: FsR: AddToStore without UID

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#523]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point

QA: Fluids Report: ADD POST without UID – Size (1 pt)

**Comment by TessForGithub2** [comment]
Update: Special case, deferred in priority to after Happy Path & Sanity Testing is completed.

**Comment by shehzadsidi** [comment]
Just tested in QA.  The Fluid Report is successfully created even if the Fluid Report UID not passed in which is in line with the Schema Definition of Fluid Report UID being optional.  Closing the card.

-<xsd:attribute name="uid" type="witsml:uidString" use="optional">
-<xsd:annotation>
 <xsd:documentation>The unique identifier of an object. This should not be used for child nodes within an object. For an independent object, the value may be globally unique. For a dependent object, the value must be unique (for the same object type) within the context of the parent object. There should be no assumption as to the semantic content of this attribute. The purpose of this type is to facilitate modifying the optionality in derived schemas.</xsd:documentation>
 </xsd:annotation>
