### ISSUE TITLE
QA: FsRe: AddToStore with UID that already exists

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#524]
EPIC:
#491 Fluids Report Implementation
PARENT:
#493 Add to Store (C) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point

QA: Fluids Report: POST with UID that already exists – Size (1 pt)
--

**Comment by TessForGithub2** [comment]
Update: Duplicate Card. Closed.
