### ISSUE TITLE
DEV: Fluids Report: Construct DOT Call for GET with UID Only

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#526]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492  Get from Store (R) Fluids Report Object
SIZE:
16 hours = 2 days = 4 points

DEV: Fluids Report: Construct and Drill Ops Town (DOT) call for GET with UID only and includes UID => UUID mapping  Size (4 pts)

**Comment by niaalex** [comment]
This item is in progress and 50% complete. @sukhendumukherjee

**Comment by sukhendumukherjee** [comment]
Dev Complete
