### ISSUE TITLE
DEV: Fluids Report: Get Response Conversion 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#527]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object
SIZE:
12 hours = 1 1/2 days = 3 points

DEV: Fluids Report: Get Response Conversion  – Size (3pts)

**Comment by niaalex** [comment]
This is dependent on the in progress WITSML object @TessForGithub2 
ETA is 7/25 for WITSML object

**Comment by sukhendumukherjee** [comment]
Dev Complete
