### ISSUE TITLE
DEV: Fluids Report: Get Response Mapping  

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#528]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object
SIZE:
12 hours = 1 1/2 days = 3 points

DEV: Fluids Report: Get Response Mapping  – Size (3pts)

**Comment by niaalex** [comment]
In progress at 30% complete 
ETA - 7/26 @sukhendumukherjee

**Comment by sukhendumukherjee** [comment]
Dev Complete
