### ISSUE TITLE
DEV: FsR: Construct Graph QL DOT Call 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#530]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object
SIZE:
16 hours = 2 days = 4 points

DEV: Fluids Report: Construct Graph QL DOT Call – Size (4pts)

**Comment by niaalex** [comment]
@sukhendumukherjee  will confirm if this is still valid. ETA for update noon 7/25.

**Comment by sukhendumukherjee** [comment]
We are not using grapgql and we can close this.
