### ISSUE TITLE
DEV: FsR: Response Conversion Graph QL 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#531]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object
SIZE:
12 hours = 1 1/2 days = 3 points

DEV: Fluids Report: Response Conversion Graph QL – Size (3pts)

**Comment by niaalex** [comment]
@sukhendumukherjee will confirm if this is still valid. ETA for update noon 7/25.

**Comment by sukhendumukherjee** [comment]
We are not using grapgql and we can close this.
