### ISSUE TITLE
QA:FsR:GetFromStore with Object Selection

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#533]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object
SIZE:
12 hours = 1 1/2 days = 3 points

QA: Fluids Report: GET with Object Selection - Size – (3pts)

**Comment by TessForGithub2** [comment]
Update: Shehzad will start this test case on 7/25. It will provide a Full Transaction, vanilla sanity testing, in priority order of 1.4.1.1, 1.3.1.1, and 2.0.

ETA: 7/25

Separate card will be opened to address 1.3.1.1 and 2.0

**Comment by TessForGithub2** [comment]
Update: Special case, deferred to after Happy Path & Sanity Testing complete.

**Comment by shehzadsidi** [comment]
Duplicate card, closing

**Comment by niaalex** [comment]
@shehzadsidi  What is the card number for the other one that this one duplicated ?
