### ISSUE TITLE
DEV: FsR: UPDATE in Store Get Identity /Patch Call 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#534]
EPIC:
#491 Fluids Report Implementation
PARENT:
#494 Update from Store (U) Fluids Report Object
SIZE:
8 hours = 1  day = 2 points

DEV: Fluids Report: UPDATE in Store Get Identity /Patch Call  - Size 2pts (1 day)

**Comment by TessForGithub2** [comment]
Update: This has been completed under a different card.
