### ISSUE TITLE
QA: FsR: DeleteFromStore - Entire Object 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#539]
EPIC:
#491 Fluids Report Implementation
PARENT:
#495 Delete from Store (D) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point
QA: Fluids Report: Delete Entire Object – Size (1pt) – 1/2 day

**Comment by TessForGithub2** [comment]
Update: This is the Happy Path & Sanity test for DeleteFrom Store. ETA: 7/29

**Comment by niaalex** [comment]
@shehzadsidi what is the current status on this item including the planned ETA?

**Comment by shehzadsidi** [comment]
Successfully tested in Container 0.17.0.  Closing the card
