### ISSUE TITLE
QA: Fluids Report: Delete element 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#540]
EPIC:
#491 Fluids Report Implementation
PARENT:
#495 Delete from Store (D) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point
QA: Fluids Report: Delete element – Size (1pt) – 1/2 day

**Comment by niaalex** [comment]
@shehzadsidi  what is the current status on this item including the planned ETA?

**Comment by shehzadsidi** [comment]
The delete functionality for happy path tested for Container 0.17.0.  Currently testing extended test cases (Delete by element) for container 0.17.1. ETA 8/5 (COB)

**Comment by shehzadsidi** [comment]
Testcases ready.. will test and complete by 8/7 COB
