### ISSUE TITLE
QA: FsR: Delete cascading 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#541]
EPIC:
#491 Fluids Report Implementation
PARENT:
#495 Delete from Store (D) Fluids Report Object
SIZE:
4 hours = 1/2 day = 1 point
QA: Fluids Report: Delete cascading – Size (1pt) – 1/2 day

**Comment by shehzadsidi** [comment]
When the well or wellborn deleted, all subsequent objects underneath gets deleted as well.  Closing the card.
