### ISSUE TITLE
DEV: Fluids Report: Request Object Selection Capability True 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#544]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get From Store Fluids Report Object 
SIZE:
8 hrs = 1 day = 2 points 

Dev - Request Object Selection Capability True – Return State Object with/fake data

**Comment by niaalex** [comment]
@sukhendumukherjee will deliver with 7/29

**Comment by sukhendumukherjee** [comment]
Dev Complete
