### ISSUE TITLE
DEV: Fluids Report: Options In Return Elements All - ID Only

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#545]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object
#542 
SIZE:
16 hrs = 2 days = 4 pts

DEV – Options In Return Elements All; ID Only – 4 pts

**Comment by niaalex** [comment]
@sukhendumukherjee  to cover with 7/29 delivery of FsR.

**Comment by sukhendumukherjee** [comment]
Dev Complete
