### ISSUE TITLE
QA: FsR: Validate Support for Object Selection Criteria (any combination)

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#546]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object 
SIZE:
12 hrs = 1 1/2 days = 3 pts

QA Support for Object Selection criteria (any combination) – Validation only no code req’d – 3pts based on need for additional cards

**Comment by shehzadsidi** [comment]
QA tested.. able to successfully query Fluid Report object with UID and name.  Closing the card.
