### ISSUE TITLE
QA: FsR: For return elements ID-Only 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#548]
EPIC:
#491 Fluids Report Implementation
PARENT:
#492 Get from Store (R) Fluids Report Object TBD?
SIZE:
4 hours = 1/2 day = 1 pt

QA: Fluids Report: For return elements ID-Only

**Comment by shehzadsidi** [comment]
QA tested, the Fluid Report object successfully retrieved with Fluid Report UID (with Options In: returnElements=all).  Closing the card.
