### ISSUE TITLE
QA:LOG:Index not getting the min max returned

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#551]
There is no Min and Max Index returned in the index channel.

<logs xsi:schemaLocation="http://www.witsml.org/schemas/1series http://www.witsml.org/schemas/1series/obj_log.xsd" version="1.4.1.1" xmlns="http://www.witsml.org/schemas/1series" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <log uidWell="HM_manual-testing1234" uidWellbore="WB_test1" uid="Log-depth-test10">
    <nameWell />
    <nameWellbore />
    <name />
    <objectGrowing />
    <serviceCompany />
    <runNumber />
    <pass />
    <bhaRunNumber />
    <indexType />
    <startIndex />
    <endIndex />
    <startDateTimeIndex />
    <endDateTimeIndex />
    <direction />
    <indexCurve />
    <nullValue />
    <logCurveInfo uid="">
      <mnemonic />
      <unit />
      <nullValue />
      <minIndex uom="" />
      <maxIndex uom="" />
      <minDateTimeIndex />
      <maxDateTimeIndex />
      <curveDescription />
      <typeLogData />
      <axisDefinition />
    </logCurveInfo>
    <customData>
      <queryProfile xmlns="http://www.witsml.org/schemas/131">QuepMetaDataRefresh</queryProfile>
    </customData>
  </log>
</logs>

Drillflow return:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<logs version="1.4.1.1" 
    xmlns="http://www.witsml.org/schemas/1series" 
    xmlns:ns2="http://www.energistics.org/schemas/abstract">
    <log uid="Log-depth-test10">
        <nameWell>HM_manual-testing1234</nameWell>
        <nameWellbore>WB_test1</nameWellbore>
        <name>Log depth test10</name>
        <indexType>measured depth</indexType>
        <startIndex uom="m">1000.0</startIndex>
        <endIndex uom="m">1044.0</endIndex>
        <indexCurve>Depth</indexCurve>
        <logCurveInfo uid="lci-2">
            <mnemonic>Channel1</mnemonic>
            <classIndex>0</classIndex>
            <unit>psi</unit>
            <mnemAlias>Channel1</mnemAlias>
            <minIndex uom="m">1000.0</minIndex>
            <maxIndex uom="m">1044.0</maxIndex>
            <typeLogData>double</typeLogData>
        </logCurveInfo>
        <logCurveInfo uid="lci-3">
            <mnemonic>Channel2</mnemonic>
            <classIndex>0</classIndex>
            <unit>deg</unit>
            <mnemAlias>Channel2</mnemAlias>
            <minIndex uom="m">1000.0</minIndex>
            <maxIndex uom="m">1044.0</maxIndex>
            <typeLogData>double</typeLogData>
        </logCurveInfo>
        <logCurveInfo uid="lci-1">
            <mnemonic>Depth</mnemonic>
            <classIndex>0</classIndex>
            <unit>m</unit>
            <mnemAlias>md</mnemAlias>
            <typeLogData>double</typeLogData>
        </logCurveInfo>
    </log>
</logs>

**Comment by TessForGithub2** [comment]
Update: Confirmed that Shehzad tested & it is to be closed.
