### ISSUE TITLE
DEV:LOG: Implementation of "Delete channel from ChannelSet by ChannelSet UUID and mnemonic" has a bad URL

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#553]
EPIC:
#361 Log CRUD Implementation
Card Size:
Small

While documenting Drillflow's URLs that are configurable by SLB, I noticed that the following URL does not match SLB's API:

Drillflow:
*********
https://demo.slb.com/democore/channelreader/v4/witsml/channels/:mnemonic

SLB's API:
**********
https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/{mnemonic}?channelSetUuid={channelSetUuid}

Explanation:
************
The URL to use for this REST call should be:
https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/

{mnemonic} is a variable to be provided within the REST code and is not a hard-coded part of the SLB API's URL. 

Further explanation as provided within SLB's API provides further clarity:
Delete channel from ChannelSet by ChannelSet UUID and mnemonic. Both Channel metadata and data will be deleted.

mnemonic is expected to be provided and not hard-coded.

Further Ask:
*************
Who assumes this card will need to also generate a QA card and add to Docs (envvars.rst).

**Comment by TessForGithub2** [comment]
UPDATE: I have not included this documentation into envvars.rst (Drillflow documentation) because I think this endpoint is part of the "bug":

:Variable:
    LOG_MNEMONIC_PATH
:Description:
    The path to use to get to the
:Variable:
    LOG_MNEMONIC_PATH
:Description:
    The path to use to get to the
:Default:
    https://demo.slb.com/democore/channelreader/v4/witsml/channels/:mnemonic
:Required:
    NO (default will be used)
:Example Environmental Switch in Docker:
    To set to https://prod.slb.com/channelreader/v5/witsml/channels/:mnemonicDefault:
    https://demo.slb.com/democore/channelreader/v4/witsml/channels/:mnemonic
:Required:
    NO (default will be used)
:Example Environmental Switch in Docker:
    To set to https://prod.slb.com/channelreader/v5/witsml/channels/:mnemonic

**Comment by TessForGithub2** [comment]
UPDATE: This does not appear to be implemented in the code base & Chris says that we will never use this endpoint. It is correct that is should not be included within the documentation, but it should be removed from the code base.

**Comment by shehzadsidi** [comment]
This is fixed in container 0.18.1
