### ISSUE TITLE
DEV: Create the New Container for 0.14.0 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#561]
Deliver end of Sprint 14 docker image 0.14.0.  **Please confirm that the trajectory return issue fix is captured in this container.**  

Hopefully this will address the open item c/o XiaoBin not being able to see it in 0.13.3.

For reference See Below FYI: 

XiaoBin DENG [12:10 AM]
@Mike Sturm , thanks a lot. We'll try it later

XiaoBin DENG [3:20 AM]
@Mike Sturm checked newest available docker image is still 0.13.3. What we can check is against specific version, we cannot deploy *Latest* image. I will verify it on new image version

**Comment by TessForGithub2** [comment]
UPDATE: I have generated docker image 0.14.0 last night & per Chris, it should have included the Traj fix. Shehzad will be creating a Soap UI test suite for this, but it is involved. He would have to create tests that verify every property for the Traj.
