### ISSUE TITLE
DEV:LOG: When performing a log query, a client must not provide duplicate mnemonics (error-482)

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#564]
Epic:
#361 
Size:
Medium

When a client performs a get from store query, they must not define duplicate mnemonics in the LCIs or in the mnemonics list.
From the WITSML spec:
The clients MUST NOT [else error -482] specify duplicate mnemonics in a query.

**Comment by niaalex** [comment]
JUNIT Complete and Fix Confirmed 9/13
