### ISSUE TITLE
DEV:LOG: When performing an add or update in store for log, a client must not specify duplicate mnemonics (error -447)

### ISSUE THREAD

**Issue by Mike-d-s** [hashmapinc/Drillflow#565]
Epic: #361 
Size:
Medium

When a client is doing an add to store or update in store for log, the client must not specify duplicate mnemonics in the LCIs or in the mnemonics list.

From the specification:
When adding or updating curves, a client MUST [else error -447] specify unique column-identifiers.

**Comment by TessForGithub2** [comment]
Update: Working on this card now as part of #562

**Comment by niaalex** [comment]
This will be covered in branch 395A - ETA is 7/22 @TessForGithub2

**Comment by TessForGithub2** [comment]
UPDATE: This will be fixed when df-395A is merged with Master. ETA: 9/1

**Comment by niaalex** [comment]
JUNIT Complete and Fix Confirmed 9/13
