### ISSUE TITLE
DEV: LOG Add To Store (Without Log Data Scenarios)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#566]
Add to Store for Logs needs to support the following scenarios:
1. Add Log object with Channel Set and Channels but without Log Data (Yes, Yes, No)
2. Can NOT Add Log Object with Channel Set but without Channels and Log Data (Yes, No, No)

So, Channel Set (Log Header) is MANDATORY,
      Channels                             is MANDATORY,
      Log Data                             is OPTIONAL.

As always, a Log Object is added with Channel Set, Channels, and Log Data. Do not break by adding cases 1 & 2 above.

**Comment by TessForGithub2** [comment]
UPDATE: Scenario #1 is working for both Time and Depth.
                Scenario #2 is not possible. Channels must be present; otherwise, DoT returns "missing uom" error.
                Scenario #3 is not possible. Channels must be present; otherwise, DoT returns "missing uom" error.
       
As before, All

**Comment by TessForGithub2** [comment]
UPDATE: Release in branch df-551 (PR #592)
