### ISSUE TITLE
QA: LOG: Min and Max Data values based on the Log Data for Logs 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#570]
EPIC: 
#361 Log CRUD Implementation
SIZE: 
TBD @shehzadsidi  c/o Test team will confirm 

QA: LOG: Min and Max Data values based on the Log Data for Logs

**Comment by TessForGithub2** [comment]
Update: Confirmed with Shehzad that this card is done. Closing it now.
