### ISSUE TITLE
DEV: Query (ALL) 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#581]
Query ALL Expected Min (Start) and Max (End) Including Index Channel

**Comment by TessForGithub2** [comment]
UPDATE: Verified during release of container 0.16.0 that min (Start) and max (end) including index channel was present during a "Query ALL". We are closing this card since it appears to be resolved for 1.4.1.1 and subsequent 1.3.1.1 testing will uncover if there is an issue in that version.
