### ISSUE TITLE
DEV:LOG: Extra <classIndex/> in GetFromStore()

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#593]
Reported by SLB on 6/25 by email "Issues found in Drillflow V0.14 image" by Xiangyi KONG.

"Log, an extra <classIndex/> in GetFromStore() if not specified in the request.

**Comment by niaalex** [comment]
Noted as not solved  by SLB – active in current sprint 
ETA TBD pending @TessForGithub2  RTC support bandwidth

**Comment by niaalex** [comment]
HM Dev can not duplicate the issue further analysis in progress; will be tested in QA
Verification will be provided - ETA 7/8

**Comment by niaalex** [comment]
@sukhendumukherjee will confirm this item ETA - 7/29

**Comment by sukhendumukherjee** [comment]
Dev Complete. Need to Test in QA
