### ISSUE TITLE
DEV:LOG:Index of logData is not sorted by Increasing Order

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#594]
Issue reported by SLB (refer to 6/25 email entitled "Issues found in Drillflow V0.14 image").

**Comment by niaalex** [comment]
Item noted not solved by SLB- active classified for next sprint 
ETA TBD pending @TessForGithub2 current sprint support bandwidth
--

**Comment by niaalex** [comment]
This item has been fixed/this item is now closed.
