### ISSUE TITLE
DEV:LOG:<commonData/>, <classWitsml> and <curveDesription/> missing in GetFromStore()

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#597]
As reported by SLB with email dated 6/25 entitled "Issues found in Drillflow V0.14 image":

"Log, <commonData/>, <classWitsml/> and <curveDescription/> missing in GetFromStore() Response"

**Comment by niaalex** [comment]
Noted as Solved by SLB team – HM Dev to determine needed action

**Comment by niaalex** [comment]
Dev update pending SLB field input. This item is now blocked.

**Comment by niaalex** [comment]
HM Dev needs this field from common data to validate this - <dTimLastChange></dTimLastChange>

**Comment by niaalex** [comment]
SLB team has requested additional detail about this item.  Please advise in reply to the email.

**Comment by niaalex** [comment]
@sukhendumukherjee will verify and push the code today 7/16.

**Comment by niaalex** [comment]
@sukhendumukherjee  please advise the outcome of your review on this item.  Please be reminded of the client feedback provided on this one.
Email Detail FYI: 
From: Chongwei Wan <CWan2@slb.com> 
Sent: Monday, July 15, 2019 9:34 PM
Subject: RE: [Ext] DEV:LOG:<commonData/>, <classWitsml> and <curveDesription/> missing in GetFromStore() #597 - Blocked Pending SLB Update

**Comment by sukhendumukherjee** [comment]
We are now getting <dTimLastChange>2019-07-12T19:46:13.696Z</dTimLastChange> and element is being added.Will be available with next container.

**Comment by niaalex** [comment]
@sukhendumukherjee does this update complete this issue?  If so, please close the card asap.
