### ISSUE TITLE
DEV: UpdateInStore and GetFromStore Log Data out of order (URGENT: Priority1, ShowStopper for RTC)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#609]
Perform the following to uncover the bug (test case attached)
[Result Log Data Out of Order.txt](https://github.com/hashmapinc/Drillflow/files/3339775/Result.Log.Data.Out.of.Order.txt)
[ModofyLog(Depth)Object.txt](https://github.com/hashmapinc/Drillflow/files/3339777/ModofyLog.Depth.Object.txt)
[Create Log(Depth).txt](https://github.com/hashmapinc/Drillflow/files/3339778/Create.Log.Depth.txt)

1. Create the Log (Depth) object with Log Data (AddToStore).
2. Update/Append the Log Data on existing log object (UpdateInStore)
3. Perform the retrieval (GetFromStore).
4. Verify the retrieved Log Data out of order
     <mnemonicList>Mdepth,Vdepth,Bit Dist,TQ on btm</mnemonicList>
      <unitList>m,m,m,kft.lbf</unitList>
      <data>1010.01,616.01,3.54,</data>
      <data>499,0,,</data>
      <data>501.03,0.02,,</data>
      <data>502.01,1.44,21.73,</data>
      <data>503.01,1.48,17.65,10.31</data>
      <data>504.05,0.18,1.55,15.58</data>
      <data>505.03,3.32,,</data>
      <data>510.01,616.01,3.54,</data>
      <data>610.01,616.01,3.54,</data>
      <data>710.01,616.01,3.54,</data>
      <data>810.01,616.01,3.54,</data>
      <data>910.01,616.01,3.54,</data>
   </logData>

**Comment by niaalex** [comment]
This issue was closed and the fix delivered in 0.16.0
