### ISSUE TITLE
DEV: DrillFlow unable to handle timestamps format passed in from the RTC Client (URGENT, Showstopper)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#610]
DrillFlow unable to handle timestamps format passed in from the RTC Client (URGENT, Showstopper) for associated Log Data.  The response missing the channels.  Attached is the Testcases for AddToStore and GetFromStore.  
[Add To Store Request for TimeStamp Format Issue.txt](https://github.com/hashmapinc/Drillflow/files/3346264/Add.To.Store.Request.for.TimeStamp.Format.Issue.txt)
[Get From Store Response for Timestamp Issue.txt](https://github.com/hashmapinc/Drillflow/files/3346265/Get.From.Store.Response.for.Timestamp.Issue.txt)

**Comment by niaalex** [comment]
This item was resolved in docker container 0.16.0
