### ISSUE TITLE
DEV: WITSML 1.3.1.1 (Add To Store Failing)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#622]
When calling AddToStore for creating Log objects fails in 1.3.1.1 and returns the following error:
JSONObject["logData"] is not a JSONArray.

**Comment by niaalex** [comment]
This item has been identified as a bug: Test cases have already been created is pending dev update.  Dev card created for tracking

**Comment by niaalex** [comment]
Client has provided a screen shot of how WITSML 1.3.1.1 server is connected using RTC.
See email from 
From: Chongwei Wan <CWan2@slb.com> 
Sent: Monday, July 8, 2019 7:19 PM
Please Review the email and advise if this has an impact on this card and if we are still on target to complete this card  on today (7/9) as planned
