### ISSUE TITLE
DEV: WellBore: Tech Debt for Wellbore Query with OptionsIn

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#623]
This card addresses the following: 
one issue is reported regarding wellbore query
in WATT, if query wellbore with OptionsIn "returnElements=all", the response won't contain uidWell property

Client analysis in progress.  Update pending client feedback.

**Comment by niaalex** [comment]
Client confirmed the fix via slack; HM Dev review and QA in progress.
QA will test (unblock) and close

**Comment by niaalex** [comment]
@shehzadsidi will confirm and close 7/18

**Comment by shehzadsidi** [comment]
testing successful, UIDWell property is present in WITSML response.  Closing the card.
