### ISSUE TITLE
DEV: Drillflow Trace Update

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#625]
This card is to provide an update on the tracing option.  See client email 
Subject: RE: Regarding Drillflow trace 
From: tonia.alexander@hashmapinc.com <tonia.alexander@hashmapinc.com> 
Sent: Friday, July 5, 2019 8:39 AM

Dear Tonia and HM colleagues,

This week we got time to analyze if Drillflow trace recorded in DoT ELK system is enough for trouble shooting. For the time being, it is not easy for us to do this evaluation. Take “Add new well” for example, this operation will result in over 100 traces as below (left is message list and right is details of specific message):

See email for image FYI

**Comment by niaalex** [comment]
Please note the update to this client inquiry should be in **reply all** from the email
From: XiaoBin DENG <XDeng4@slb.com> 
Sent: Monday, July 8, 2019 7:02 PM
that adds Pascal Hochart on the distro

**Comment by niaalex** [comment]
Please advise the current status of this item c/o open action item updates @TessForGithub2

**Comment by niaalex** [comment]
@cherrera2001 was this addressed already with the fix to the logging mechanism that you released yesterday?  Please advise if this is ok to close

**Comment by niaalex** [comment]
@cherrera2001 was this addressed already with the fix to the logging mechanism that you released yesterday? Please advise if this is ok to close

@cherrera2001  is this item closed  now?

**Comment by TessForGithub2** [comment]
UPDATE: Logging mechanism adequate? Advise as to priority due to end of project life.

**Comment by cherrera2001** [comment]
Yes it is fine.

**Comment by TessForGithub2** [comment]
Thanks, Chris. I will close the card now, Toni'a.
