### ISSUE TITLE
DEV:LOG:UpdateInStore Edge Case RTC Failure

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#635]
Epic: LOG

If the Index Channel in a Log Channels List does not exist, we will have to go out to DoT to get the Channel's Metadata for <indexCurve/>, convert the Channel to another Log Channel, and add it to the List.

Check that AddToStore follows suit.

Logic:
*******
If Update
Does <indexCurve/> exist in the LCI List?
If NOT,
      a. Get Channel Metadata
      b. Get <indexCurve/> metadata
      c. Convert Channel to LCI (now the "<indexCurve/> LCI")
      d. Add "<indexCurve/> LCI" to LCI List
      e. Continue from Update Query
If YES,
      Continue

**Comment by niaalex** [comment]
This item was resolved and delivered with container 0.16.0
