### ISSUE TITLE
DEV:LOG: GetFromStore 1.3.1.1 Channel Set Metadata missing objectGrowing 

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#644]
GetFromStore Log 1.3.1.1 Channel Set Metadata missing objectGrowing. Need to trace for root cause & fix.

**Comment by niaalex** [comment]
ETA is 7/24 @sukhendumukherjee

**Comment by niaalex** [comment]
@sukhendumukherjee will manage this in the next sprint

**Comment by shehzadsidi** [comment]
The issue is still outstanding.

**Comment by shehzadsidi** [comment]
QA Tested, issue is fixed.
