### ISSUE TITLE
DEV:FsR: Modify underlying architectural elements dependent upon WitsmlObject

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#651]
Now that we have the converter in the WitsmlObjects Library, we need to modify the underlying architecture elements that support the FluidsReport object in Drillflow.

**Comment by niaalex** [comment]
ETA is 7/24 (AM)  @TessForGithub2 

The associated card #642 

DEV:FR:Finish Fluids Report Converter #642

**Comment by TessForGithub2** [comment]
Update: All fluids report objects are now funneling through end-to-end in DrillFlow. Closing the card.
