### ISSUE TITLE
Docker Container 0.17.0 Delivery 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#652]
The team will not deliver the 0.16.2 container but  on Monday 7/29 will instead deliver the Docker Container 0.17.0  to cover the basic 1311 Functionality that was not captured in 0.16.1.  This container (0.17.0) will include the basic sanity test suite.

::NOTE:: A second container (0.17.1) will be delivered on 7/31 to include the full FsR test case Suite.

**Comment by niaalex** [comment]
@TessForGithub2  please advise the new ETA for the docker container.

**Comment by TessForGithub2** [comment]
ETA is Monday, 7/29. I expect it will contain all the CRUD for Fluids Report (basic sanity cases only; we will have to spend time reviewing edge cases & special cases) & 1.3.1.1 fixes.

**Comment by niaalex** [comment]
Card updated to note that the team will NOT deliver the 0.16.2 container this week but  on Monday 7/29 will instead deliver the Docker Container 0.17.0  to cover the basic 1311 Functionality that was not captured in 0.16.1.  This container (0.17.0) will include the basic sanity test suite.

::NOTE:: A second container (0.17.1) will be delivered on 7/31 to include the full FsR test case Suite.

**Comment by TessForGithub2** [comment]
Update: Update will NOT be included in container 0.17.0. I will deliver this in 0.17.1

**Comment by TessForGithub2** [comment]
Container 0.17.0 has been delivered and is in use by SLB.
