### ISSUE TITLE
DEV: QA: Review and Respond to client inquiry for “one message” split options 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#653]
Determine best option to combine multiple-line message; Client suggested options are: 

- Option a, combine multiple-line message into one line on drillflow side

- Option b, combine multiple-line message into one line on DoT side. This introduce another layer of processing before filebeat collecting on DoT side.
==============================================================
This card covers the client request Sent: Friday, July 26, 2019 3:41 AM
From: XiaoBin DENG <XDeng4@slb.com>

Mike,

Is it possible to remove (or replace with tab) below “CRLF” from one message inside?
 
See Image in Email FYI 

Currently, traces from 3rd party components are collected by Filebeat, which treats “CRLF” as end of specific message and works fine for Cassandra (Please see sample Cassandra message in attachment), RabbitMq, etc. For above Drillflow trace, this mechanism results in “one message” split:

See Image in Email FYI 
After short discussion with team members, we think there are 2 options here:
•	Option a, combine multiple-line message into one line on drillflow side
•	Option b, combine multiple-line message into one line on DoT side. This introduce another layer of processing before filebeat collecting on DoT side.

Considering developing and further maintenance effort, we prefer option a. How do you think? 

Thanks,
Xiaobin

**Comment by niaalex** [comment]
@TessForGithub2 what is the update on this item?

**Comment by TessForGithub2** [comment]
Update: We are working in priority order, and we have not yet looked into this yet.

**Comment by niaalex** [comment]
Who should this be assigned to and how should this be prioritized for noting ETA?

**Comment by TessForGithub2** [comment]
UPDATE: This ask required custom CXF code to fix. It is anticipated to take > 1 week, and Mike mentioned something about asking Chris for the fix after his vacation. However, Mike thinks a more viable alternative is IF FileBeat allows configuration for CRLF (not treating as separate message), to have them configure FileBeat to see if this is the better solution.

Mike did suggest that someone google for roughly 1 hour to see if FileBeat permits this or not. That will tell us the definitive solution (whether we have to move on to custom CXF code or not).

**Comment by niaalex** [comment]
@TessForGithub2 please advise the current status and new ETA for this item.

**Comment by TessForGithub2** [comment]
OK, this is another one I spoke with Mike about.

He said:
1. We should allocate 1 hour for someone to Google about File Beat (whether
it is true that a configuration is easy for File Beat). If true, then we
need to ask SLB is they are OK with trying it.
2. If it is false about File Beat, then it will take longer than 1 week
(Mike's estimate from discussing with Chris) for someone to provide CXF
custom code to fix it.

I can drop this status into the card if you would like.

Thank you,

Theresa Stewart
281.723.7108

**Comment by niaalex** [comment]
Yes I remember that update but who owns the action?

 

Based in what I reviewed in Google it seems to be easy but I think that is relative to who will actually have to do the work.  Lets say the dev team determines this is more involved, who will own the action to provide CXF custom code to fix it?

 

This is the update I need.

**Comment by TessForGithub2** [comment]
Mike said Chris would do it. I do not know what kind of arrangement they
have with Chris because that shocked me. But he mention it earlier this
week, after it was know that Chris is gone.

**Comment by niaalex** [comment]
Acknowledged / thank you.

 

I will Assign Mike for now

**Comment by niaalex** [comment]
@Mike-d-s please advise the status of this item; this is being tracked in the status deck.

**Comment by Mike-d-s** [comment]
@cherrera2001 I see the other closed card, I assume we can close this one too?

**Comment by cherrera2001** [comment]
@Mike-d-s make it so number 1.

**Comment by Mike-d-s** [comment]
Closed as per feedback.
