### ISSUE TITLE
DEV: FsR DeleteFromStore Failed with full template (default delete template in WATT)

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#677]
DeleteFromStore is OK with simplified template, but failed with full template(which is default delete template in WATT
<?xml version=“1.0” encoding=“utf-16"?>
<fluidsReports xmlns=“http://www.witsml.org/schemas/1series” xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” xsi:schemaLocation=“http://www.witsml.org/schemas/1series  ../xsd_schemas/obj_fluidsReport.xsd” version=“1.4.1.1">
<fluidsReport uidWell=“W-0820” uidWellbore=“WB-0820" uid=“FR-0820”>
  <nameWell>Well 0820</nameWell>
  <nameWellbore>WB 0820</nameWellbore>
  <name>FluidsReport 0820</name>
  <dTim></dTim>
  <md uom=“”></md>
  <tvd uom=“”></tvd>
  <numReport></numReport>
  <fluid uid=“”>
    <type></type>
    <locationSample></locationSample>
    <density uom=“”></density>
    <visFunnel uom=“”></visFunnel>
    <tempVis uom=“”></tempVis>
    <pv uom=“”></pv>
    <yp uom=“”></yp>
    <gel10Sec uom=“”></gel10Sec>
    <gel10Min uom=“”></gel10Min>
    <gel30Min uom=“”></gel30Min>
    <filterCakeLtlp uom=“”></filterCakeLtlp>
    <filtrateLtlp uom=“”></filtrateLtlp>
    <tempHthp uom=“”></tempHthp>
    <presHthp uom=“”></presHthp>
    <filtrateHthp uom=“”></filtrateHthp>
    <filterCakeHthp uom=“”></filterCakeHthp>
    <solidsPc uom=“”></solidsPc>
    <waterPc uom=“”></waterPc>
    <oilPc uom=“”></oilPc>
    <sandPc uom=“”></sandPc>
    <solidsLowGravPc uom=“”></solidsLowGravPc>
    <solidsCalcPc uom=“”></solidsCalcPc>
    <baritePc uom=“”></baritePc>
    <lcm uom=“”></lcm>
    <mbt uom=“”></mbt>
    <ph></ph>
    <tempPh uom=“”></tempPh>
    <pm uom=“”></pm>
    <pmFiltrate uom=“”></pmFiltrate>
    <mf uom=“”></mf>
    <alkalinityP1 uom=“”></alkalinityP1>
    <alkalinityP2 uom=“”></alkalinityP2>
    <chloride uom=“”></chloride>
    <calcium uom=“”></calcium>
    <magnesium uom=“”></magnesium>
    <potassium uom=“”></potassium>
    <rheometer uid=“”>
      <tempRheom uom=“”></tempRheom>
      <presRheom uom=“”></presRheom>
      <vis3Rpm></vis3Rpm>
      <vis6Rpm></vis6Rpm>
      <vis100Rpm></vis100Rpm>
      <vis200Rpm></vis200Rpm>
      <vis300Rpm></vis300Rpm>
      <vis600Rpm></vis600Rpm>
    </rheometer>
    <brinePc uom=“”></brinePc>
    <lime uom=“”></lime>
    <electStab uom=“”></electStab>
    <calciumChloride uom=“”></calciumChloride>
    <company></company>
    <engineer></engineer>
    <asg></asg>
    <solidsHiGravPc uom=“”></solidsHiGravPc>
    <polymer uom=“”></polymer>
    <polyType></polyType>
    <solCorPc uom=“”></solCorPc>
    <oilCtg uom=“”></oilCtg>
    <hardnessCa uom=“”></hardnessCa>
    <sulfide uom=“”></sulfide>
    <comments></comments>
  </fluid>
  <commonData>
    <itemState></itemState>
    <comments></comments>
  </commonData>
</fluidsReport>
</fluidsReports> 

The client is referring to this as an inconsistency between Fluids Reports and Log/Traj since Log/Traj handles a full transaction.  High Priority.

**Comment by Mike-d-s** [comment]
validated that a delete entire object (no sub elements) and delete sub element are both working now).  Note that client should not provide elements with data in a deleted query.
