### ISSUE TITLE
Creation of a Mock REST API endpoint

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#7]
Child of #32
In order to test the application functionality we will need a mock rest api endpoint. This solution will not have to do anything except respond with expected and/or unexpected REST error or success codes.

**Comment by niaalex** [comment]
@cathyhashmap this item has been assigned to you. Please review and advise the ETA.

**Comment by cherrera2001** [comment]
The point of this task is to create a fake endpoint for testing that exposes the same api's so that we can code against it. Not to test the rest api's themselves...the title is a bit misleading there

**Comment by cherrera2001** [comment]
This is now done as part of hashmap/drilltest
