### ISSUE TITLE
OptionsIn Library Util

### ISSUE THREAD

**Issue by deepa7kumar** [hashmapinc/Drillflow#70]
The OptionsIn parameter there are potentially multiple options in formatted as per 6.1.7 on page 43 of the 1.4.1.1 Spec. Additionally for 1.3.1.1 it should be noted that options in will be null or empty string.
The options in needs to be parsed correctly. I suggest adding a utility library that does this, as it will need to be done for other functions. It would be nice to have a com.hashmapinc.tempus.witsml.server.util library that holds static functions such as this.

**Comment by cherrera2001** [comment]
For additional clarification:

The options in parameter is formatted as per the spec: 

keyword1=value1
keyword1=value1;keyword2=value2
keyword1=value1;keyword2=value2;keyword3=value3

I would like a util class that would translate this into a Map<String,String> where the values would be:

keyword1,value1
keyword2,value2
keyword3,value3

The valid keywords start on page 55 of the 1.4.1.1 spec.

the pseudo-code is

```java
Map<String,String> convertOptionsIn(String optionsIn){
    Map<String,String> options = new HashMap<>();
    String[] kvpairs = optionsIn.split(";");
    foreach(kvpairs kvpair){
           option[] = kvpair.split("=");
           options.add(option[0],option[1]);
    }
    return options;
} 
```
