### ISSUE TITLE
Implement filtered querying from the DotDelegator

### ISSUE THREAD

**Issue by randypitcherii** [hashmapinc/Drillflow#91]
Child of #46
Requires #89
Requires #105

Given a `QueryContext`, parse the context into a number of REST queries to the DoT REST endpoint and collect the resulting data in a sensible way to pass to the translator for processing back into the proper WITSML object POJO for that object type and witsml version

**Comment by randypitcherii** [comment]
Do this for WELLs only

**Comment by randypitcherii** [comment]
![image](https://user-images.githubusercontent.com/8570256/48868696-31272780-eda0-11e8-901b-7f7894be9630.png)

**Comment by randypitcherii** [comment]
During the conversion, make sure the JSON object is in WITSML 1.4.1.1 format. 

The DoT server now returns WITSML 1.4.1.1 values in JSON format. We can use this to our advantage because of the existing support for this version in the `WitsmlObjects` library

**Comment by randypitcherii** [comment]
Please see further design discussions at https://github.com/hashmapinc/Drillflow/issues/46

**Comment by randypitcherii** [comment]
BLOCKED - need a drilltest api to build this against

**Comment by vijaypoojari** [comment]
Working on conversion of POJO to XML. ETA for task completion is 12 EST today.
