### ISSUE TITLE
Perform query validation at the df-server level for addToStore

### ISSUE THREAD

**Issue by randypitcherii** [hashmapinc/Drillflow#98]
See the WITSML 1.3.1.1 and 1.4.1.1 specs for rules on query validation.

Create a df-server RequestValidator object with static validation methods that validate input to GetFromStore, UpdateInStore, DeleteFromStore, and AddToStore.

Refer to the 1311 and 1411 spec for validation rules for each method and return the proper error code in each validation method. 

DO NOT mutate the inputs.

Child of #257

**Comment by niaalex** [comment]
@vijaypoojari @randypitcherii  - Vijay please advise the status/ETA for this item.

**Comment by niaalex** [comment]
@vijaypoojari is this item still open?

**Comment by vijaypoojari** [comment]
@niaalex finalizing test cases for it.

**Comment by niaalex** [comment]
@vijaypoojari  I didn't see the update on this one closing yesterday.  Were there issues?
@cherrera2001
